### ISSUE TITLE
License not included

### ISSUE THREAD

**Issue by BastianZim** [retep998/winapi-rs#1014]
Hi, when downloading `winapi-x86_64-pc-windows-gnu:0.4.0` and `winapi-i686-pc-windows-gnu:0.4.0` no license files are included. Not sure why because they are specified in the `Cargo.toml`.

Ref:
* https://github.com/retep998/winapi-rs/blob/5b1829956ef645f3c2f8236ba18bb198ca4c2468/x86_64/Cargo.toml#L9
* https://github.com/retep998/winapi-rs/blob/5b1829956ef645f3c2f8236ba18bb198ca4c2468/i686/Cargo.toml#L9

**Comment by ankane** [comment]
It looks like they were added on June 7, 2018, which is after the 0.4.0 release (on January 17, 2018).

**Comment by BastianZim** [comment]
Ahh yes that makes sense – thanks.
