### ISSUE TITLE
MAKEINTRESOURCE macro

### ISSUE THREAD

**Issue by roblabla** [retep998/winapi-rs#104]
Winuser.h defines a macro that is used a fair bit : [MAKEINTRESOURCE](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648029%28v=vs.85%29.aspx).

> Converts an integer value to a resource type compatible with the resource-management functions. This macro is used in place of a string containing the name of the resource. 

```
#define MAKEINTRESOURCEA(i) ((LPSTR)((ULONG_PTR)((WORD)(i))))
#define MAKEINTRESOURCEW(i) ((LPWSTR)((ULONG_PTR)((WORD)(i))))
```

Would it be within the scope of this crate to reimplement this macro for inclusion inside winuser.rs ?

**Comment by retep998** [comment]
It would if the macro did anything. As it is, it's nothing more than a type cast, not even any bitshifts.

**Comment by Eh2406** [comment]
So if we are not going to implement it, can this be closed?
