### ISSUE TITLE
Update winmm-sys (and other out of date crates) on crates.io

### ISSUE THREAD

**Issue by randomPoison** [retep998/winapi-rs#123]
The version of winmm-sys on crates.io is pretty out of date, when I tried to pull it down on a new machine it didn't have some of the functions I needed even though they're present on master. I don't know what other crates are affected. Also the link to documentation that shows up on crates.io is out of date and doesn't give a valid page.

**Comment by retep998** [comment]
Should be fixed by https://github.com/retep998/winapi-rs/commit/156b222ac3410ae269f3f32b5c9a246878a78b53 although until all the -sys crates are bumped, old doc links will remain on crates.io.

**Comment by bungcip** [comment]
I also got some problem when I want to use comdlg32-sys.  crates.io version is out of date.

**Comment by Eh2406** [comment]
Are this fixed? Can we close?

**Comment by bozaro** [comment]
[version-sys 0.0.1](https://crates.io/crates/version-sys) is out of date too

**Comment by retep998** [comment]
winapi 0.3 has all these functions from the -sys crates and is published, so this issue is no longer relevant.
