### ISSUE TITLE
mmap constants are missing

### ISSUE THREAD

**Issue by danburkert** [retep998/winapi-rs#139]
The Following mmap constants are missing, as documented [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366761(v=vs.85).aspx):

* `FILE_MAP_READ`
* `FILE_MAP_WRITE`
* `FILE_MAP_ALL_ACCESS`
* `FILE_MAP_COPY`
* `FILE_MAP_EXECUTE`

**Comment by iliekturtles** [comment]
I have these defined in my fork. I'll clean things up and submit a PR tomorrow if no one else has gotten to it.

https://github.com/iliekturtles/winapi-rs/commit/45f94da4f19836a8e61e6b112e2622f1f440f14d
