### ISSUE TITLE
Split code into modules

### ISSUE THREAD

**Issue by retep998** [retep998/winapi-rs#17]
Currently `lib.rs` is a massive file which makes editing difficult, and can bring certain editors to a crawl.

* [x] Move code from each header into separate module
* [x] Split libraries into separate crates
* [ ] Get rid of ugly `::` everywhere as soon as glob imports aren't broken.

**Comment by retep998** [comment]
A design plan has been figured out which doesn't depend on recursive imports. However once recursive imports work correctly the code can be cleaned up.

**Comment by retep998** [comment]
Glob imports will be working correctly in Rust 1.4, so hopefully next year I can begin the transition.

**Comment by Eh2406** [comment]
What are the next steps, now that we are well past 1.4?

**Comment by retep998** [comment]
First I stop procrastinating and land the various PRs that are hanging around in limbo. Then once I'm caught up I experiment with removing `::` everywhere.

**Comment by retep998** [comment]
Actually I think I'd like to move things further into submodules based on the subfolder names so it would be `winapi::um::d3d11` for example instead of just `winapi::d3d11`. This would break any code that refers to the submodules explicitly so I'll have to wait for winapi 0.3 for this change.

**Comment by retep998** [comment]
Replaced by https://github.com/retep998/winapi-rs/issues/316
