### ISSUE TITLE
kernel32-sys fails to build (link)

### ISSUE THREAD

**Issue by globin** [retep998/winapi-rs#193]
When building kernel32-sys:
```
F:\Rust\bin\cargo.exe build -v
       Fresh winapi-build v0.1.1 (file:///F:/dev/winapi-rs/lib/kernel32-sys)
   Compiling kernel32-sys v0.1.4 (file:///F:/dev/winapi-rs/lib/kernel32-sys)
     Running `F:\dev\winapi-rs\lib\kernel32-sys\target\debug\build\kernel32-sys-8e0909f63b633aae\build-script-build`
       Fresh winapi v0.2.2 (file:///F:/dev/winapi-rs/lib/kernel32-sys)
failed to run custom build command for `kernel32-sys v0.1.4 (file:///F:/dev/winapi-rs/lib/kernel32-sys)`
Process didn't exit successfully: `F:\dev\winapi-rs\lib\kernel32-sys\target\debug\build\kernel32-sys-8e0909f63b633aae\build-script-build` (exit code: -1073741515)
```

**Comment by retep998** [comment]
How does this even. I don't even. What is your version of Rust (`rustc -vV`)?

**Comment by globin** [comment]
```
cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-10)
```

```
rustc 1.2.0 (082e47636 2015-08-03)
binary: rustc
commit-hash: 082e4763615bdbe7b4dd3dfd6fc2210b7773edf5
commit-date: 2015-08-03
host: x86_64-pc-windows-gnu
release: 1.2.0
```

**Comment by retep998** [comment]
Downloaded the exact same build of Rust/Cargo, made sure the versions matched, I did a `cargo test` on winapi which builds `kernel32-sys` and everything went fine. Something is weird with your setup, and I have no idea what it is.

What is the output of `systeminfo`?
What is your `PATH`?
Which terminal are you using? cmd? Powershell? Msys2?
Can you run `F:\dev\winapi-rs\lib\kernel32-sys\target\debug\build\kernel32-sys-8e0909f63b633aae\build-script-build` manually and see if it is panicking? Maybe debug it and get a backtrace or figure out why it is crashing?

**Comment by globin** [comment]
Wow, windows..
Rebooted in the mean time and now it's working.. Don't get it.. Sorry
