### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by flip111** [retep998/winapi-rs#194]
When i go to the crates.io site and click documentation a lot of crates get a 404 on the docs:

https://crates.io/crates/crypt32-sys
https://crates.io/crates/d3d9-sys
https://crates.io/crates/dbghelp-sys
https://crates.io/crates/dsound-sys
https://crates.io/crates/dwmapi-sys
https://crates.io/crates/gdi32-sys
https://crates.io/crates/opengl32-sys
https://crates.io/crates/oleaut32-sys
https://crates.io/crates/ole32-sys
https://crates.io/crates/ktmw32-sys
https://crates.io/crates/psapi-sys
https://crates.io/crates/secur32-sys
https://crates.io/crates/vssapi-sys
https://crates.io/crates/xinput-sys
https://crates.io/crates/uuid-sys

Some have documentation availabel like this one:

https://crates.io/crates/shell32-sys

I was looking for a function to create a progress bar, how can i find this function?

**Comment by retep998** [comment]
Typically the easiest way to get to the documentation is to get there from the main `winapi` crate (https://retep998.github.io/doc/winapi/).
Then you can use the sidebar on the left to navigate between crates. If a crate isn't there, that means I haven't generated documentation for it.

If you want to know how to create a progress bar, what you should actually do is lookup how to do it on MSDN. For example, on https://msdn.microsoft.com/en-us/library/windows/desktop/bb760816%28v=vs.85%29.aspx where it tells you:

>You can create a progress bar by using the CreateWindowEx function, specifying the PROGRESS_CLASS window class.

If you then go to the documentation for `CreateWindowEx` (https://msdn.microsoft.com/en-us/library/windows/desktop/ms632680%28v=vs.85%29.aspx) you will see that its respective library is `user32.lib`, therefore `CreateWindowExW` should be defined in `user32-sys`. `PROGRESS_CLASS`, like everything that isn't a function, is defined in `winapi`.

**Comment by flip111** [comment]
Thanks for the explanation!
