### ISSUE TITLE
Get WinMain parameters?

### ISSUE THREAD

**Issue by chrisxue815** [retep998/winapi-rs#201]
Hi all,

I'm wondering if there's a way to get the four parameters (hInstance, hPrevInstance, lpCmdLine, nCmdShow) in WinMain(), especially nCmdShow.

Solutions:
* hInstance:
`let hInstance = kernel32::GetModuleHandleW(ptr::null());`
* hPrevInstance: ?
* lpCmdLine: `env::args().skip(1)`
* nCmdShow: ?

**Comment by retep998** [comment]
The MSDN documentation on `hPrevInstance ` states:

>A handle to the previous instance of the application. This parameter is always NULL.

`nCmdShow` can easily be obtained (along with a bunch of other stuff) via `GetStartupInfo`.

**Comment by chrisxue815** [comment]
Thanks for your answer!
