### ISSUE TITLE
FILE_*_INFO bindings

### ISSUE THREAD

**Issue by danburkert** [retep998/winapi-rs#211]
`winapi` is currently lacking bindings for the file info structs used by [`SetFileInformationByHandle`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365539(v=vs.85).aspx) and [`GetFileInformationByHandleEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364953(v=vs.85).aspx).  The full set of types is listed by the [`FILE_INFO_BY_HANDLE_CLASS`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364228(v=vs.85).aspx) enum.  These APIs are useful for file operations beyond what `std::fs` provides.

**Comment by Mart-Bogdan** [comment]
I can't use this `ENUM!` it don't create actual enum, and don't introduce names into winapi::um::minwinbase
