### ISSUE TITLE
#[derive(Default)]

### ISSUE THREAD

**Issue by Eh2406** [retep998/winapi-rs#227]
HI, Thank you so much for this great product!

I just noted that my code has a lot of 
```
    let mut msg = winapi::MSG {
        hwnd: ptr::null_mut(),
        message: 0,
        wParam: 0,
        lParam: 0,
        time: 0,
        pt: winapi::POINT {
            x: 0,
            y: 0,
        },
    };
```
and
```
        let mut status = winapi::SPVOICESTATUS {
                                        ulCurrentStream: 0,
                                        ulLastStreamQueued: 0,
                                        hrLastResult: 0,
                                        dwRunningState: 0,
                                        ulInputWordPos: 0,
                                        ulInputWordLen: 0,
                                        ulInputSentPos: 0,
                                        ulInputSentLen: 0,
                                        lBookmarkId: 0,
                                        PhonemeId: 0,
                                        VisemeId: winapi::SP_VISEME_0,
                                        dwReserved1: 0,
                                        dwReserved2: 0,
        };
```
I am new to rust, but i think this in an improvement on 
```
    unsafe {
        let mut clsid_spvoice: winapi::CLSID = mem::uninitialized();
    }
```

which can be found in the wild at: https://github.com/Connorcpu/markovify/blob/master/src/tts.rs#L86

Does it make sense to add #[derive(Default)] to thas structs?

-----

I can make the pull request but I need some advice about if there are structs that should not #[derive(Default)] and how to tell.

**Comment by retep998** [comment]
The recommended option is actually
`let mut msg = winapi::MSG = unsafe { mem::zeroed() };`

While I would like to add `#[derive(Default)]`, it would unfortunately cause a massive amount of extra codegen which would make compile times significantly worse.

**Comment by Eh2406** [comment]
Is tare some way to do that as a impl instead of #[derive(Default)]

```
impl Default for <T> {
    fn default() -> <T> {
        unsafe { mem::zeroed() }
    }
}
```

**Comment by retep998** [comment]
When I get all the structs switched over to `STRUCT!` I will experiment with something like that to see whether I can do it without adversely affecting compile times.

**Comment by Eh2406** [comment]
getting converted to over to `STRUCT!` ... is that something a novice like me can do to help?

**Comment by retep998** [comment]
Well first I'd have to write the `STRUCT!` macro and make sure it works correctly, but then converting everything over to use it should be trivial work that a novice could do fairly easily.

**Comment by Eh2406** [comment]
in General cleanup you added `STRUCT!` and started replacing  `#[repr(C)] #[derive(Clone, Copy, Debug)] pub struct` with it, would it be helpful for me to replace all `#[repr(C)] #[derive(Clone, Copy, Debug)] pub struct` with it? are there any I should skip?

**Comment by retep998** [comment]
All `#[repr(C)] #[derive(Clone, Copy, Debug)] pub struct` should be okay to replace. Structs with a different set of derived traits or different repr should be skipped for now so I can figure out how to deal with them.
