### ISSUE TITLE
Build fails with latest 1.6 nightly under Windows due to missing ucrt.lib

### ISSUE THREAD

**Issue by vadz** [retep998/winapi-rs#234]
I'm actually trying to install rustfmt with `cargo install --git https://github.com/nrc/rustfmt --verbose` but as I'm getting
```
...
   Compiling kernel32-sys v0.1.4
...
error: linking with `link.exe` failed: exit code: 1104
note: LINK : fatal error LNK1104: cannot open file 'ucrt.lib'
error: aborting due to previous error
```
I thought it would be more appropriate to report it here, please let me know if I was wrong.

This is using https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-msvc.msi

**Comment by retep998** [comment]
This is an issue with Rust, not with winapi. Please open an issue in the Rust repo for this.

winapi and friends do not link `ucrt.lib`

**Comment by retep998** [comment]
I just tested `cargo install --git https://github.com/nrc/rustfmt --verbose` on my machine using the same version of Rust with VS 2015 installed with the Windows 10 SDK installed, and it worked fine. There's something different about your VS or Windows SDK setup that is confusing Rust.

**Comment by vadz** [comment]
Thanks for the hints, I hadn't even realized that `ucrt.lib` was the universal CRT from MSVS 2015 and not something Rust-specific. I do have MSVS 2015 installed (as well as a few older versions), but I have no idea how does the SDK detection process works nor where to start debugging it. I'll try to look into it later.

**Comment by retep998** [comment]
The relevant code is in https://github.com/rust-lang/rust/blob/master/src/librustc_trans/back/msvc/mod.rs

You'd have to do a bit of digging to figure out what Windows SDKs you have installed, and what your various registry settings are, in order to understand what decisions that code in rustc is making and how to improve them.

**Comment by vadz** [comment]
I've updated MSVS 2015 to the latest Update 1 RC and I don't see this problem any more.

I really don't see how could this have fixed it, to be honest, it seems more likely that the reboot required by this update (grrr...) did it. So there might still be something really wrong somewhere but as it doesn't happen here any more, I'll just close this, sorry for bothering you.

**Comment by retep998** [comment]
It's okay. Getting Rust to correctly work under all the ways in which someone has VS installed is tricky, and there's likely to be edge cases like yours where things break apart. If you do ever encounter any issues though with Rust on Windows, feel free to get in touch with me and I'll try to help.
