### ISSUE TITLE
Windows Eventlog

### ISSUE THREAD

**Issue by stephanbuys** [retep998/winapi-rs#235]
Hi there,

Is there a way to read the Windows Eventlog using your library?

Regards,
Stephan

**Comment by retep998** [comment]
I assume you're referring to https://msdn.microsoft.com/en-us/library/windows/desktop/aa385780%28v=vs.85%29.aspx
That would be `wevtapi-sys` and `winevt.rs` which don't have any bindings yet. Feel free to fill them in though!

**Comment by stephanbuys** [comment]
@retep998 I'm not quite there with my rust foo, and not a Windows programmer :) But I'll keep this issue open in case someone wants to step in. It would be awesome if this (http://www.ogris.de/eventlogreader/EventLogReader.cpp) could be ported, maybe later this year I'll try!

**Comment by retep998** [comment]
Implemented in https://github.com/retep998/winapi-rs/commit/ea9cb5d2e83e7936b5d43e5b7bbe3891921f4844
