### ISSUE TITLE
SORRY FOR BREAKING EVERYTHING

### ISSUE THREAD

**Issue by retep998** [retep998/winapi-rs#238]
I published a new major version of `kernel32-sys`, from `0.1.4` to `0.2.0`.
Some crates bumped their dependency to `kernel32-sys = "0.2"`.
`kernel32-sys` specifies `links = "kernel32"`.
Cargo only allows **one** dependency to specify `links = "foo"` for any given `foo`.
`kernel32-sys` is often depended on unconditionally because Cargo lacks good platform specific dependencies.
`kernel32-sys` is a transitive dependency of most projects even on non-windows.
Many projects ended up transitively depending on both `kernel32-sys = "0.2"` and `kernel32-sys = "0.1"`.
`0.2` and `0.1` are semver incompatible and so are considered separate unique dependencies.
Cargo refuses to let them both specify the same `links`.
Everything breaks.

Sorry.

Issues in other projects caused by this:
https://github.com/PistonDevelopers/conrod/issues/622
https://github.com/rust-lang-deprecated/time/issues/126
https://github.com/zonyitoo/shadowsocks-rust/issues/16
https://github.com/tomaka/glutin/issues/656
https://github.com/PistonDevelopers/piston/issues/1004
https://github.com/dpc/mioco/issues/60
https://github.com/maidsafe/routing/pull/766
https://github.com/maidsafe/crust/issues/408

**Comment by mitchmindtree** [comment]
Maybe it's worth finding (or posting) an issue at cargo that we can link this issue to.

**Comment by Dashed** [comment]
For the time being, I'm editing the `Cargo.lock` file to lock down and use a single version of `kernel32-sys`.

**Comment by laanwj** [comment]
The workaround that I used is to make a `.cargo/config` file with 
```
paths = ["/home/user/projects/winapi-rs"]
```
Pointing it to my own check-out of winapi-rs. This succeeds in making all dependencies use the same version of winapi-rs, of course if the API is incompatible they may cause compile issues later on. But it seems to work for me.

**Comment by Dashed** [comment]
Thanks for the fix @retep998 ! :+1: 

I can happily report that updating to `0.2.1` gives no problems.
