### ISSUE TITLE
Windows XP and new functions

### ISSUE THREAD

**Issue by davidkazlauskas** [retep998/winapi-rs#257]
I've cross compiled some stuff from Win8 and tried to use that DLL in WinXP. It said "The procedure entry point GetFileInformationByHandleEx could not be located in the dynamic link library KERNEL32.dll".

Seems like that function was too new and didn't exist in windows xp back in the day. So, I hacked around by removing it from building (patch below). Now the stuff runs on XP, however, I believe the best way to address this would be to add cfg variables to build for certain versions where, for instance, if I specify to build for XP this function wouldn't be touched.

```
diff --git a/lib/kernel32/src/lib.rs b/lib/kernel32/src/lib.rs
index 8d65a7f..f967060 100644
--- a/lib/kernel32/src/lib.rs
+++ b/lib/kernel32/src/lib.rs
@@ -1039,10 +1039,6 @@ extern "system" {
     pub fn GetFileInformationByHandle(
         hFile: HANDLE, lpFileInformation: LPBY_HANDLE_FILE_INFORMATION,
     ) -> BOOL;
-    pub fn GetFileInformationByHandleEx(
-        hFile: HANDLE, FileInformationClass: FILE_INFO_BY_HANDLE_CLASS, lpFileInformation: LPVOID,
-        dwBufferSize: DWORD,
-    ) -> BOOL;
     pub fn GetFileMUIInfo(
         dwFlags: DWORD, pcwszFilePath: PCWSTR, pFileMUIInfo: PFILEMUIINFO,
         pcbFileMUIInfo: *mut DWORD,
diff --git a/tests/kernel32.rs b/tests/kernel32.rs
index 96786cc..12f3419 100644
--- a/tests/kernel32.rs
+++ b/tests/kernel32.rs
@@ -582,7 +582,6 @@ fn functions() {
     bb(GetFileAttributesW);
     bb(GetFileBandwidthReservation);
     bb(GetFileInformationByHandle);
-    bb(GetFileInformationByHandleEx);
     bb(GetFileMUIInfo);
     bb(GetFileSize);
     bb(GetFileSizeEx);
```

**Comment by retep998** [comment]
The way linking is done, any functions which are unused will not remain in the resulting binary. If there are unused functions which are still in the resulting binary then that is a bug which needs to be investigated.

**Comment by retep998** [comment]
I just did a quick test with `x86_64-pc-windows-msvc` creating a DLL which did depend on `kernel32-sys` and use some things from it and it only ended up depending on things which were actually used. In particular I did not see a dependence on `GetFileInformationByHandleEx`.

**Comment by davidkazlauskas** [comment]
Oh, ok, I guess this can be closed then.

**Comment by retep998** [comment]
Just tested `x86_64-pc-windows-gnu` and that seems to be behaving fine as well. You claim that you fixed the issue by just removing that definition from `kernel32-sys`. Are you sure that was all you did? `kernel32-sys` has a ton of functions that shouldn't work on XP.

**Comment by davidkazlauskas** [comment]
Oh, yeah, I also removed GetFileInformationByHandleEx from fs2 library. Now I didn't touch winapi crate, just removed reference from fs2 and also objdump doesn't show GetFileInformationByHandleEx function present. Thanks for help.
