### ISSUE TITLE
SetWindowLong vs SetWindowLongPtr

### ISSUE THREAD

**Issue by pravic** [retep998/winapi-rs#285]
For x86 `SetWindowLongPtr` is just a macro substitution for `SetWindowLong`, and [user32-sys](https://github.com/retep998/winapi-rs/blob/master/lib/user32/src/lib.rs#L992-L997) declares `SetWindowLongPtr` only for x64, because x86 user32.dll has no `Ptr` version.

But what about `SetWindowLongPtr` usage? We can implement it in `user32-sys`, but winapi-rs prefers no executable code as mentioned in #218. Or we can write the portable stub for x86/x64 in every rusty crate, which tries to use the user32.

Any better solutions for this?

**Comment by retep998** [comment]
For winapi 0.3 functions will be defined in file corresponding to the header they are from since I will be getting rid of the -sys crate nonsense. Thus you'd also be able to reexport functions under different names (as well as defining shim functions that call functions) since everything would be in the same crate.

**Comment by pravic** [comment]
I meeting plans about 0.3 from time to time, but is any roadmap and dates about it? Just to be aware of it.

**Comment by retep998** [comment]
There have never been any dates or roadmaps for winapi. It'll happen once I catch up on all the PRs, get the license situation squared away (I want to make all the copyrights consistent and switch to dual licensing MIT/apache), and then finally start overhauling stuff. It'll happen in bursts whenever I feel sufficiently motivated.

**Comment by retep998** [comment]
I have added re-exports for these functions so you can now use `SetWindowLongPtrW` even on `i686-pc-windows`.
