### ISSUE TITLE
Bump runtimeobject-sys

### ISSUE THREAD

**Issue by Boddlnagg** [retep998/winapi-rs#301]
Could you please push a new version of runtimeobject-sys to crates.io (with the changes from #281)?

**Comment by Boddlnagg** [comment]
Note that using runtimeobject-sys is currently only possible with the MSVC toolchain. The GNU linker fails due to at least two missing symbols:
```
undefined reference to `RoGetErrorReportingFlags@4'
undefined reference to `RoUninitialize@0'
```
The latter I have already [reported as a MinGW bug](https://sourceforge.net/p/mingw-w64/bugs/540/).

**Comment by retep998** [comment]
I could actually create a `.def` file and create my own MinGW import libraries which would fix the issue for gnu targets. Then again, I could also create my own msvc import libraries that way so someone on linux could use the `x86_64-pc-windows-msvc` target of Rust combined with LLD in link.exe mode to get native Windows targeting without any MinGW cruft or proprietary blobs at all.

Anyway, `runtimeobject-sys = "0.2"`.

**Comment by retep998** [comment]
I created https://github.com/retep998/winapi-rs/issues/302 to track the creation of my own import libraries using `.def` files.
