### ISSUE TITLE
Missing define for STILL_ACTIVE constant

### ISSUE THREAD

**Issue by ipetkov** [retep998/winapi-rs#309]
Was interested in polling a child process handle to see if it was running. According to the [GetExitCodeProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683189%28v=vs.85%29.aspx) docs, a special constant `STILL_ACTIVE` is used to denote currently running processes.

Tried to search the docs for a define for this, even grepped this repo but wasn't able to find a definition. Currently have the constant defined in my project (tests work fine with the value) but it would be great to have it available upstream.

**Comment by retep998** [comment]
`um::minwinbase::STILL_ACTIVE` in winapi 0.3
