### ISSUE TITLE
WNDCLASSA missing

### ISSUE THREAD

**Issue by hectorgrey** [retep998/winapi-rs#326]
Simple point, really; is this a design decision, or just an oversight?

**Comment by retep998** [comment]
Both `WNDCLASSW` and `WNDCLASSEXW` are defined. I don't know why you'd ever want to use the `A` versions of something, as you'll lose any semblance of unicode sanity that way. However it is an oversight that `WNDCLASSA` is missing.

**Comment by hectorgrey** [comment]
In part to make it easier to write code that doesn't use the standard library (not entirely sure how I'd encode strings as wide character strings without the stuff in standard, since Rust doesn't support them natively).

**Comment by retep998** [comment]
If you're doing `no_std` shenanigans, you can always use `MultiByteToWideChar` with `CP_UTF8`. Note that winapi 0.2 still requires std anyway. The work in progress winapi 0.3 will support `no_std` projects.

**Comment by alexchandel** [comment]
I need the `WNDCLASSA` as well. `RegisterClassA` and `RegisterClassExA` should also be added.
