### ISSUE TITLE
Suggestion: Maybe we can provide a Form(not dialog) application sample

### ISSUE THREAD

**Issue by smithfox** [retep998/winapi-rs#346]
The example in README.md is brief "Hello, World!" message dialog.

Maybe we can write "Hello, World!" Form，that contains RegisterClassExW, CreateWindowExW, Message Loop, **Menu**。

Rust language itself has a steep learning curve, coupled with the use of windows SDK to write GUI program, it is even more difficult. 

If there is a good example, that can make a lot of beginners like me feel a little confidence.

Maybe it's not winapi-rs job, but it will help Rust community grow faster.

After all, on https://crates.io site, winapi-rs is the 2th most downloaded.

**Comment by Plasticcaz** [comment]
I was looking for just such a thing earlier today. Why was this closed.

It was not obvious to me (and still isn't to be honest) how to get the hInstance for opening a window from the documentation.

**Comment by retep998** [comment]
@Plasticcaz All information you would normally get from `WinMain` can be acquired through `GetModuleHandle` `GetStartupInfo` and `std::env::args`.
