### ISSUE TITLE
Virtual Listview

### ISSUE THREAD

**Issue by JesperAxelsson** [retep998/winapi-rs#349]
Hi!
I have been trying to create a virtual listview with winapi following several guides written i C and C++. But when I try this in rust the item is not shown for some reason. Is this a winapi bug or am I doing something wrong? 

I have setup a repo with the code:
https://github.com/JesperAxelsson/rust-virtual-listview

**Comment by JesperAxelsson** [comment]
I got it working, was a simple logic error on my part. Let me know if you want to use the code as a sample. I can change the license as well if you want.

**Comment by retep998** [comment]
You're terminating your wide strings with _two_ nulls?? https://github.com/JesperAxelsson/rust-virtual-listview/blob/master/src/main.rs#L44-L45
Not that there is anything wrong with it, but a single null is generally sufficient.

**Comment by JesperAxelsson** [comment]
I am pretty new to rust, didn't know what the chain(once(0)) did, thanks for the tip!

**Comment by JesperAxelsson** [comment]
Not issue with winapi.
