### ISSUE TITLE
Question: What is the status of the Windows Registry API?

### ISSUE THREAD

**Issue by zsck** [retep998/winapi-rs#353]
Hello!

I'm looking into the level of support here for the Windows Registry API.  I found a [pull request](https://github.com/retep998/winapi-rs/pull/23) from a couple of years ago that appears to implement a lot of it, but cannot find any of the functions listed in the PR by searching the repo.

Have these functions been moved, removed, or just renamed to something I can't find?

Thanks!

**Comment by retep998** [comment]
For winapi 0.2, which is what is currently available on crates.io, you can access the registry functions from the `advapi32-sys` crate. https://retep998.github.io/doc/advapi32/fn.RegCreateKeyExW.html

**Comment by zsck** [comment]
Awesome, thank you!
