### ISSUE TITLE
Missing IID_IUnknown GUID

### ISSUE THREAD

**Issue by alexchandel** [retep998/winapi-rs#355]
The GUID for `IID_IUnknown` appears to be missing. It should be `00000000-0000-0000-C000-000000000046`

**Comment by alexchandel** [comment]
Also missing `IID_IClassFactory`, which should be `00000001-0000-0000-C000-000000000046` I believe.

**Comment by alexchandel** [comment]
I'm not sure about the byte order of either of those though.

**Comment by retep998** [comment]
All interfaces now have associated uuids which you can access via a `uuidof` method, such as `IUnknown::uuidof()`. Because this is done via an `Interface` trait, you can leverage this for smart pointer wrappers to do stuff like `QueryInterface` safer.
