### ISSUE TITLE
IsEqualGUID is neither exposed from ole32 nor implemented

### ISSUE THREAD

**Issue by alexchandel** [retep998/winapi-rs#356]
`IsEqualGUID` is implemented inline in src/shared/guiddef.rs, but not exposed, and the ole32 function is commented out. Could you enable one of these?

**Comment by retep998** [comment]
`IsEqualGUID` will be usable in winapi 0.3 https://github.com/retep998/winapi-rs/blob/dev/src/shared/guiddef.rs#L32-L34

**Comment by alexchandel** [comment]
Any chance these minor additions could leak out before 3.0?

**Comment by retep998** [comment]
Probably not, I'm focusing exclusively on 0.3 now. However, it should be fairly easy to define that function yourself since it is just comparing public fields.

**Comment by retep998** [comment]
winapi 0.3 is published and has a usable `IsEqualGUID`.
