### ISSUE TITLE
Broken implementation of winuser::INPUT, must use largest variant

### ISSUE THREAD

**Issue by alexchandel** [retep998/winapi-rs#36]
The implementation you provide for INPUT is broken. The union field is too small to contain any of its variants, as it is type `()`.

Given the state of union support in Rust, the only declaration that produces a correctly sized struct is declaring the struct with the largest, most-aligned variant, as I did in my [pull request](https://github.com/retep998/winapi-rs/pull/33).

Thus this:
```rust
#[repr(C)] #[derive(Copy)] pub struct INPUT {
    pub type_: ::DWORD,
    pub union_: MOUSEINPUT,
}
```

rather than this:
```
#[repr(C)] #[derive(Copy)] pub struct INPUT {
    pub type_: ::DWORD,
    pub union_: (), // FIXME - Use unions or unsafe enums here somehow
}
```

I get that it's a fixme, but it's also unusable right now. I'd basically have to declare my own INPUT with the correct size and pass that to `SendInput()`, ignoring this altogether.

For now, using the largest variant will guarantee the correct size of the struct, and will allow `transmute_copy`s of all three union variants into the `union_` field.

Could you fix this?

**Comment by retep998** [comment]
What if I provided a generic parameter for `INPUT` so that it would look like this?
```rust
#[repr(C)] #[derive(Copy)] pub struct INPUT<T> {
    pub type_: i32,
    pub union_: T,
}
```

**Comment by alexchandel** [comment]
That's a good idea. I'm unsure if it will work though: [SendInput](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310%28v=vs.85%29.aspx) says it takes the "The size, in bytes, of an INPUT structure" as an argument.

It warns that "If cbSize is not the size of an INPUT structure, the function fails" but it fails to specify what size or sizes (if multiple) it considers valid. I know it succeeds when passed `sizeof(INPUT)` in C, and when passed `size_of::<INPUT>()` in Rust if `struct INPUT` has the same size as its C equivalent.

**Comment by retep998** [comment]
The fact that it takes the size means it should allow for the structure to vary in size. I'll implement it and then you can test it and tell me if it functions correctly.

**Comment by alexchandel** [comment]
I suppose one could always just pass it `size_of::<INPUT<MOUSEINPUT>>()` regardless of what pointer you actually pass it, but then you risk the function attempting to write to `*mut INPUT<KEYBDINPUT>` like it's a `*mut INPUT<MOUSEINPUT>`, and corrupting your stack.

**Comment by alexchandel** [comment]
Sounds good.

**Comment by retep998** [comment]
See 729f893aae3432e238f80edc3730885071b1c9c2

**Comment by alexchandel** [comment]
@retep998 `INPUT_generic` does not work for KEYBDINPUT or HARDWAREINPUT. One would assume that the Windows APIs only accept something that is the size of *the* INPUT struct.

Until Rust has better support for C unions, I would declare all Rust unions using the largest, most-aligned variant. This ensures that they're correctly sized and aligned, precludes stack corruption by win32 functions, and saves in headaches. I think my original PR had the best declaration:
```rust
#[repr(C)] #[derive(Copy)] pub struct INPUT {
    pub type_: ::DWORD,
    pub union_: MOUSEINPUT,
}
``

**Comment by retep998** [comment]
Oh well, I guess I'm stuck with that until we have proper untagged unions.
At least I've added a test to ensure that `MOUSEINPUT` really is the largest most-aligned variant.
076b54e513c1650b6e7c81d1f92feada5f58bf80

**Comment by alexchandel** [comment]
Cool, I'll be able to depend on this for keyboard/mouse scripting now. VN bump soon?
