### ISSUE TITLE
Send marker for handles

### ISSUE THREAD

**Issue by DenisKolodin** [retep998/winapi-rs#360]
It seems `HWND`, `HANDLE`, etc. could implement `Send`. Why not add this marker?

**Comment by retep998** [comment]
Because they are raw pointers so I am incapable of implementing `Send` on them. The solution here is for you to wrap them inside some sort of safe wrapper type and then unsafely impl `Send` on the wrapper type.

**Comment by DenisKolodin** [comment]
Now I see, thank you!
