### ISSUE TITLE
dcomp/dwrite_1,2,3 suporrt

### ISSUE THREAD

**Issue by ekicyou** [retep998/winapi-rs#362]
I am Japanese. This document is an automatically translated document.
In order to make an application using layered window,
The title api is required.

1. dcomp-sys is registered with cargo, but is there any plan to implement it?
2. Similarly, is there a prospect of responding to dwrite_1,2,3?
3. I would like to contribute to development if possible, but do you have development guides?

* dcomp.h / dcompanimation.h
   windows surface composition engine.
   Reference [High-Performance Window Layering Using the Windows Composition Engine](https://kennykerr.ca/2014/06/02/high-performance-window-layering-using-the-windows-composition-engine/)

* dwrite_1.h
  * Support for vertical writing characters such as Japanese.

* dwrite_2.h, dwrite_3.h
  * Font cache and correspondence to Web fonts.
  * Strengthen layout relationship.

**Comment by retep998** [comment]
Winapi is currently undergoing an organizational overhaul (https://github.com/retep998/winapi-rs/issues/316) which means that there will be no more updates to the -sys crates. Instead all the functionality you need will be in `winapi` itself.

It is intended to bind all of dcomp and dwrite in winapi eventually.

There are guidelines for contributing: https://github.com/retep998/winapi-rs/blob/dev/CONTRIBUTING.md

**Comment by ekicyou** [comment]
Destructive changes on win10 sdk and found that is in progress. see comtributing.md and check the 0.3 series. 

Thank you.
