### ISSUE TITLE
Usage example in README

### ISSUE THREAD

**Issue by ArtemGr** [retep998/winapi-rs#37]
So with the new crate structure how do I use, say, `PlaySoundA`?

With
```
[dependencies.winapi]
git = "https://github.com/retep998/winapi-rs"
```
and
```
winapi::winmm-sys::PlaySoundA
```
all I get is the `unresolved name winapi::winmm` error.

**Comment by retep998** [comment]
The functions are stored in separate crates. The easiest way to use `PlaySoundA` is like this.
```toml
[dependencies]
winapi = "*"
winmm-sys = "*"
```
```rust
extern crate winapi;
extern crate "winmm-sys" as winmm;
fn func() {
    winmm::PlaySoundA(...);
}
```

**Comment by ArtemGr** [comment]
So you're actually pushing all those crates to crates.io? I see, thanks.

**Comment by retep998** [comment]
Yes, I pushed all 420 of those `-sys` crates to crates.io.

**Comment by ArtemGr** [comment]
Woot!

**Comment by retep998** [comment]
An example has been added to `README.md`.
