### ISSUE TITLE
setupapi-rs is still at version 0.0.1

### ISSUE THREAD

**Issue by dhylands** [retep998/winapi-rs#386]
It would be nice if a version which matched winapi 0.2.8 could be released.

I've been using the 0.2 branch version and it seems to be working fine, but in order to release a crate I need a working version (and 0.0.1 doesn't even compile with the latest stable rust).

**Comment by retep998** [comment]
This issue is no longer relevant as winapi 0.3 has been published and has all the setupapi functions.
