### ISSUE TITLE
How to interface with the same method?

### ISSUE THREAD

**Issue by ekicyou** [retep998/winapi-rs#389]
How to interface with the same method?

```rust
RIDL!(#[uuid(0x4d93059d, 0x097b, 0x4651, 0x9a, 0x60, 0xf0, 0xf2, 0x51, 0x16, 0xe2, 0xf3)]
interface IDCompositionVisual(IDCompositionVisualVtbl): IUnknown(IUnknownVtbl) {
    fn SetOffsetX(
        offsetX: c_float
    ) -> HRESULT,
    fn SetOffsetX(
        animation: *const IDCompositionAnimation
    ) -> HRESULT,
  ...
```

→*error[E0124]: field `SetOffsetX` is already declared*

**Comment by retep998** [comment]
The thing about COM interfaces is that the names themselves don't actually matter. The only thing that matters is the uuid, the signatures of the methods (but not their names!), and the number and order of the methods. You could easily rename them to `SetOffsetX1` and `SetOffsetX2` or provide other more descriptive names.

**Comment by ekicyou** [comment]
Thanks! rename seq number.
