### ISSUE TITLE
HANDLE types should support Sync trait

### ISSUE THREAD

**Issue by lzybkr** [retep998/winapi-rs#396]
I'm new to Rust, so if my understanding is misguided, do let me know.

I'm trying to use a handle - `HMODULE` in a static `HashMap`. This is not allowed because the trait `std::marker::Sync` is not satisfied on `*mut winapi::HINSTANCE__`.

I think `DECLARE_HANDLE` should define a type that supports the `Sync` trait.
Handles are not pointers even though they're defined that way in `winnt.h`.

**Comment by retep998** [comment]
You should be wrapping your handles in a newtype so that you can do stuff like automatically closing the handle when dropped. One of the benefits of such a wrapper is you can assert that it is thread safe like so:
```Rust
struct Handle(HANDLE);
unsafe impl Sync for Handle {}
```
Related issue: https://github.com/retep998/winapi-rs/issues/360

**Comment by lzybkr** [comment]
I see.

Does it make sense for `winapi` to define a wrapper type for at least some handle types?  So for example, you could have a `Raw` type that is the pointer, and the wrapper type?

This would also introduce a level of type safety that isn't present in C/C++ with Windows handles.

**Comment by retep998** [comment]
`winapi` is strictly raw bindings. It does not attempt to provide wrappers (aside from the minimal amount for COM interfaces) or make anything safe. Anyone is free to create their own library on top of `winapi` which provides thread safe wrappers.
