### ISSUE TITLE
XINPUT_KEYSTROKE misses the "Flags" field

### ISSUE THREAD

**Issue by yoanlcq** [retep998/winapi-rs#451]
At [https://github.com/retep998/winapi-rs/blob/master/src/um/xinput.rs#L117](https://github.com/retep998/winapi-rs/blob/master/src/um/xinput.rs#L117)  
Correct definition should be
```rust
STRUCT!{struct XINPUT_KEYSTROKE {
    VirtualKey: WORD,
    Unicode: WCHAR,
    Flags: WORD, // <- Previously missing
    UserIndex: BYTE,
    HidCode: BYTE,
}}
```
Edit: [Link to the reference for convenience](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.xinput_keystroke(v=vs.85).aspx)

**Comment by retep998** [comment]
Good catch. This will be fixed in my next commit.

**Comment by retep998** [comment]
Fixed in https://github.com/retep998/winapi-rs/commit/ea9cb5d2e83e7936b5d43e5b7bbe3891921f4844
