### ISSUE TITLE
GCC required?

### ISSUE THREAD

**Issue by oconnor0** [retep998/winapi-rs#457]
While attempting to build `ripgrep` which depends on `kernel32-sys`, I get the following build failure. Is `kernel32-sys` supposed to depend upon gcc for linking?

> error: could not exec the linker `gcc`: The system cannot find the file specified. (os error 2)
>   |
>   = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\crt2.o" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "C:\\Users\\Oconnor\\AppData\\Local\\Temp\\cargo-install.ciXgAus0CClB\\release\\build\\kernel32-sys-348a96c32394e657\\build_script_build-348a96c32394e657.0.o" "-o" "C:\\Users\\Oconnor\\AppData\\Local\\Temp\\cargo-install.ciXgAus0CClB\\release\\build\\kernel32-sys-348a96c32394e657\\build_script_build-348a96c32394e657.exe" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\Oconnor\\AppData\\Local\\Temp\\cargo-install.ciXgAus0CClB\\release\\deps" "-L" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bstatic" "C:\\Users\\Oconnor\\AppData\\Local\\Temp\\cargo-install.ciXgAus0CClB\\release\\deps\\libbuild-709320f6af62dd0b.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libstd-8e63ce3235d91f56.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libpanic_unwind-7a8f267e1f472275.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librand-cbaabb050663bb1e.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcollections-0e863adcb979d99b.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc-2fe699c323a9fcd5.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc_system-1a9ffce435c6813e.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libunwind-f8f46edb99891d80.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liblibc-913fac93272423bb.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libstd_unicode-72685d3c05b2de5b.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcore-6796d5cf3cb4eed3.rlib" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcompiler_builtins-13752c636400e0ca.rlib" "-Wl,-Bdynamic" "-l" "advapi32" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-Wl,-Bstatic" "-l" "gcc_eh" "-l" "pthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\Oconnor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"
> 
> error: aborting due to previous error(s)
> 
> error: Could not compile `kernel32-sys`.
> Build failed, waiting for other jobs to finish...

**Comment by retep998** [comment]
Rust has to link binaries using a linker and because you're using `i686-pc-windows-gnu` the linker Rust uses is `gcc`. This failure is not winapi's fault however, but a recent regression in Rust itself.

https://github.com/rust-lang/rust/issues/42422

**Comment by retep998** [comment]
Fixed upstream.
