### ISSUE TITLE
dxguid fails to build on nightly

### ISSUE THREAD

**Issue by torkleyy** [retep998/winapi-rs#458]
I'm not sure if this is related to this repo, but our AppVeyor CI builds are failing on beta and nightly channel.

The error message does not seem to be particularly helpful:

```
Caused by:
  process didn't exit successfully: `rustc --crate-name dxguid C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\dxguid-sys-0.2.0\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=e6ed05839a70ac27 -C extra-filename=-e6ed05839a70ac27 --out-dir C:\projects\amethyst\target\debug\deps -L dependency=C:\projects\amethyst\target\debug\deps --extern winapi=C:\projects\amethyst\target\debug\deps\libwinapi-97963d09fc19ffa3.rlib --cap-lints allow` (exit code: 3221225501)
Build failed, waiting for other jobs to finish...
error: build failed
```

[Here the complete log](https://ci.appveyor.com/project/amethyst/amethyst/build/1.0.336/job/1gg0nmj81hj67t4s)

**Comment by retep998** [comment]
That exit code corresponds to `STATUS_ILLEGAL_INSTRUCTION` which means `intrinsic::abort`. Because it is not a compile error but rather rustc crashing, this means this is a regression in Rust itself, so you should open an issue with [Rust](https://github.com/rust-lang/rust).

**Comment by torkleyy** [comment]
@retep998 Thanks for the fast response!

**Comment by retep998** [comment]
The corresponding Rust issue (https://github.com/rust-lang/rust/issues/42544) has been fixed.
