### ISSUE TITLE
GetResourceAllocationInfo corruption

### ISSUE THREAD

**Issue by kvark** [retep998/winapi-rs#469]
Using this function produces D3D12 CORRUPTION error. Suggested fix by @msiglreith :
```rust
fn GetResourceAllocationInfo(
        &mut self, __ret_val: *mut ::D3D12_RESOURCE_ALLOCATION_INFO, visibleMask: ::UINT, numResourceDescs: ::UINT,
        pResourceDescs: *const ::D3D12_RESOURCE_DESC
    ) -> *mut ::D3D12_RESOURCE_ALLOCATION_INFO,
```

**Comment by kvark** [comment]
This is only applicable to 0.2 and should be fixed in 0.3. Closing.

**Comment by retep998** [comment]
It wasn't actually fixed at the time you closed this issue, but it is fixed now. It's a good thing I switched to a `#[fixme]` attribute marking those functions, so it was trivial to swap the order of parameters to fix the issue.

**Comment by pravic** [comment]
@retep998 How `[fixme]` works? Or it is just a part of patterns in `RIDL` macro?

**Comment by retep998** [comment]
@pravic It's just an arbitrary string that the `RIDL!` macro matches on and results in a simple transformation to account for an ABI difference.
