### ISSUE TITLE
winapi::psapi::PSAPI_WORKING_SET_BLOCK should be union

### ISSUE THREAD

**Issue by joshlf** [retep998/winapi-rs#482]
[`PSAPI_WORKING_SET_BLOCK`](https://docs.rs/winapi/0.2.8/x86_64-pc-windows-gnu/winapi/psapi/struct.PSAPI_WORKING_SET_BLOCK.html) is defined as follows:

```rust
#[repr(C)]
pub struct PSAPI_WORKING_SET_BLOCK {
    pub Flags: ULONG_PTR,
    pub BitFields: ULONG_PTR,
}
```

However, according to [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684902(v=vs.85).aspx), it's actually a union of the two fields:

```c
typedef union _PSAPI_WORKING_SET_BLOCK {
  ULONG_PTR Flags;
  struct {
    ULONG_PTR Protection  :5;
    ULONG_PTR ShareCount  :3;
    ULONG_PTR Shared  :1;
    ULONG_PTR Reserved  :3;
    ULONG_PTR VirtualPage  :20;
  };
} PSAPI_WORKING_SET_BLOCK, *PPSAPI_WORKING_SET_BLOCK;
```

**Comment by retep998** [comment]
This has already been corrected in the repo and will be available via crates.io when `0.3` is published.
https://github.com/retep998/winapi-rs/blob/dev/src/um/psapi.rs#L87-L96
