### ISSUE TITLE
[COM/OLE] IID definitions

### ISSUE THREAD

**Issue by JoeyAcc** [retep998/winapi-rs#492]
I'm having some trouble locating the `IID`s for e.g. `IID_IXMLDOMDocument`.

The IIDs are defined in the windows code itself, but I can't find them anywhere in `winapi-rs`. 
This is unfortunate as I can't find the magick number associated with `IID_IXMLDOMDocument` online either. The closest I've come is the contents of [this](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjopv_HhfrVAhXGKlAKHSw8BOYQFggmMAA&url=http%3A%2F%2Fmicrosoft.public.vc.atl.narkive.com%2FBbJ8uRqV%2Ferror-in-linking-step&usg=AFQjCNGrjJkJEBKpSP-jbxed-hgGLjHLkA) file, but all that shows is that there is more magick backing the macro constants.

So, to make COM/OLE workable, could the various IIDs be added to the appropriate crate?

**Comment by Susurrus** [comment]
The windows API is quite a big API and winapi-rs relies on user contributions to flesh it out. Would you be willing to submit a PR adding the various IIDs you're missing to the `dev` branch? That'll be the fastest route to get them added. See the `CONTRIBUTING.md` document to help you get started or post questions here if you need help. IRC is also a good way to resolve any questions quickly.

**Comment by JoeyAcc** [comment]
In principle I am willing to contribute, but I currently don't have access to the actual magic numbers.  Therefore, I can't even add them to my own project, let alone to `winapi-rs`.
The reason for that is that definition like `#define FOO __uuidof(BAR)` is not all that informative in terms of the information needed, and that's the core issue here for me.

I was hoping you (or another `winapi-rs` developer) had access to those magick values.

**Comment by Susurrus** [comment]
The magic numbers are all in the header files available within the Windows SDK. If you install it (get it [here](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk)) and then you can search the `%PROGRAMFILES%\Microsoft SDKs\Windows` directory for the specific values you need.

**Comment by retep998** [comment]
With winapi 0.3 you'll be able to do `IFoo::uuidof()` at the very least.

**Comment by retep998** [comment]
winapi 0.3 has been published and `IFoo::uuidof()` works to get the IID of any given `IFoo` interface.
