### ISSUE TITLE
user32::FindWindowEx and user32::FindWindow don't log to kernel32::GetLastError()

### ISSUE THREAD

**Issue by Xatenev** [retep998/winapi-rs#525]
It seems the functions FindWindowEx and FindWindow don't log to kernel32::GetLastError().

Code:
```
let mut window:winapi::windef::HWND = std::ptr::null_mut();
kernel32::SetLastError(23427);
loop {
            let a = std::ptr::null_mut();
            let b = std::ptr::null_mut();
            let c = std::ptr::null_mut();
            let d = program.nameASCII.as_ptr();
            let mut e: u32 = 0;
            window = user32::FindWindowExW(a,b,c,d);
            e = kernel32::GetLastError();
            println!("FIRST {}", e);
            user32::GetWindowThreadProcessId(window, &mut program.pid);

            if(kernel32::GetLastError() == 0) {
                println!("BREAK {}", "WOW");
                break;
            } else {
                println!("CONTINUE {}", kernel32::GetLastError());
                std::thread::sleep(std::time::Duration::from_millis(1000));
                continue;
            }
        }
```

Output:
```
FIRST 23427
CONTINUE 1400
FIRST 1400
CONTINUE 1400
FIRST 1400
CONTINUE 1400
FIRST 1400
CONTINUE 1400
FIRST 1400
CONTINUE 1400
FIRST 1400
CONTINUE 1400
FIRST 1400
CONTINUE 1400
FIRST 1400
CONTINUE 1400
```

As you can see - on the first call GetLastError() is 23427 because I've set it manually before. Afterwards it is always 1400 which comes from GetWindowThreadProcessId. The FindWindow error is not being logged.

In https://msdn.microsoft.com/de-de/library/windows/desktop/ms681385(v=vs.85).aspx the error codes are described: 

ERROR_INVALID_WINDOW_HANDLE
1400 (0x578)
Invalid window handle.

BTW: FindWindowExW itself returns 0x0 if I do println!("{:?}", window); on success it should print something like 0xe07b8

**Comment by retep998** [comment]
Unfortunately `winapi` can do nothing about this. Those functions are directly from system DLLs and if they don't behave as documented then that is Microsoft's fault.

**Comment by Xatenev** [comment]
@retep998 Weird since somebody from #winapi (freenode) said that he tried pretty much the same with C++ and it logged to GetLastError(). Something else must be wrong then I guess...
