### ISSUE TITLE
Using winapi on Linux doesn't typecheck

### ISSUE THREAD

**Issue by soc** [retep998/winapi-rs#532]
I'm getting a lot of

```
error[E0433]: failed to resolve. Could not find `shell32` in `winapi`
```

errors, so development of Windows-specific code is pretty much impossible on Linux.

To be clear, I don't expect the code to link or run, but it should be possible to develop code without being forced to reboot to get type-checking working, considering that Rust has all the information it needs regardless of the platform it is running on.

**Comment by retep998** [comment]
The answer is to install the windows target using rustup and then `cargo check --target x86_64-pc-windows-msvc`. Alternatively you can use appveyor as a way of checking your code for you.

**Comment by soc** [comment]
Thanks for the help!
