### ISSUE TITLE
sockaddr_in6 has disappeared from version 0.3

### ISSUE THREAD

**Issue by dimbleby** [retep998/winapi-rs#533]
`sockaddr_in6` used to be defined [here](https://github.com/retep998/winapi-rs/blob/77588710a683e1a4ec085b0f3d6c8939ecc7f030/src/ws2ipdef.rs#L36-L42); but I don't find anything similar in the 0.3 branch.  (The `SOCKADDR_IN` is [still defined](https://github.com/retep998/winapi-rs/blob/d8290fc406c8e390101dd225f7ec506848fc86ce/src/shared/ws2def.rs#L324-L329)).

Was this accidental or deliberate?  If accidental, any chance of a fix?

Thanks!

**Comment by retep998** [comment]
This was accidental.

**Comment by retep998** [comment]
Fixed by https://github.com/retep998/winapi-rs/pull/535.
