### ISSUE TITLE
how could i constructor a NOTIFYICONDATAW_u which is UNION and field is private?

### ISSUE THREAD

**Issue by woodgear** [retep998/winapi-rs#545]
i' am try to use *winapi::um::shellapi::NOTIFYICONDATAW* and find the field u is a *NOTIFYICONDATAW_u* which is a UNION.
how could i constructor  it？
[NOTIFYICONDATAW ](https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/shellapi/struct.NOTIFYICONDATAW.html)

**Comment by retep998** [comment]
`std::mem::zeroed()`
