### ISSUE TITLE
Split functions from constants and structures

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [retep998/winapi-rs#553]
Would it be possible to split off the functions to their own modules to make it possible to have fallbacks when manually loading libraries. That would make it possible to use xinput when the library is available and otherwise not.

**Comment by retep998** [comment]
The definitions of functions in the modules is not the real issue here. The issue is linking itself, and the set of import libraries that are available for linking. As long as I am constrained by the import libraries available in the Windows SDK, there is little I can do to solve a variety of dilemmas.

**Comment by Invisible-Rabbit-Hunter** [comment]
Splitting the functions from constants and structs does however let me use the LoadLibrary* functions to load the library and manually loading the functions I need, while still having access to the structures and constants that the library requires.

**Comment by retep998** [comment]
If you don't actually *use* a function from `winapi`, then no reference to the function is emitted in the resulting object file. It will still ask the linker to link that library, but with no references to the library, there will be no imports in the binary, allowing your program to run on systems without that library so you can `LoadLibrary` to your heart's content.

**Comment by Invisible-Rabbit-Hunter** [comment]
I did not know that. Thanks, you solved a problem I thought i had, but didn't actually.
