### ISSUE TITLE
When should I use kernel32 vs winapi?

### ISSUE THREAD

**Issue by gnzlbg** [retep998/winapi-rs#558]
Kernel32 depends on ^0.2.5 winapi, and from the docs of either it is not clear to me when should I use one or the other.

It also seems that I need to add `winapi` as a dependency to be able to use kernel32 anyways.

**Comment by crlf0710** [comment]
winapi 0.2 = winapi + kernel32-sys + ...
winapi 0.3 = winapi `[with features choosing what you want]`

**Comment by gnzlbg** [comment]
Thanks you can close this, I switched Rocío winapi 0.3. Maybe you could
mention this in the read me.
