### ISSUE TITLE
GetTickCount64 missing

### ISSUE THREAD

**Issue by valpackett** [retep998/winapi-rs#563]
Hi, I'm trying to migrate [systemstat](https://github.com/myfreeweb/systemstat) to winapi 0.3.

The `kernel32` crate included this function: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411(v=vs.85).aspx

I can't find it anywhere here…

**Comment by retep998** [comment]
Did you try searching the documentation?

https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/sysinfoapi/fn.GetTickCount64.html
