### ISSUE TITLE
There should be some crate-level doc on other platforms.

### ISSUE THREAD

**Issue by vi** [retep998/winapi-rs#569]
When [just open winapi in docs.rs](https://docs.rs/winapi/0.3.4/i686-unknown-linux-gnu/winapi/), you see an empty crate unless switch the target.

There should be some little text suggesting to switch the target to view the docs, like this:

`The winapi crate contains nothing on non-Windows platforms. Switch to x86_64-pc-windows-msvc to see the actual content.`

**Comment by retep998** [comment]
That would require a more complicated way of disabling the crate on non-windows than the current solution of `#![cfg(windows)]`.

**Comment by vi** [comment]
Shall `rustdoc` handle such wide crate-level `cfg`s specially then and show generic message mentioning the failed cfg?

Are there any other crates which use `#![cfg(...)]`?

**Comment by retep998** [comment]
Really I'm just hoping docs.rs will finally implement the default target support it's been promising for a while now.

**Comment by retep998** [comment]
docs.rs now supports default target, so this issue has been resolved.
