### ISSUE TITLE
Private struct `SYSTEM_INFO_u`

### ISSUE THREAD

**Issue by tathanhdinh** [retep998/winapi-rs#570]
This would be a stupid question but I still cannot figure out how to use the tuple struct [`SYSTEM_INFO_u`](https://github.com/retep998/winapi-rs/blob/0.3/src/macros.rs#L256). For example, I've used:

`let u = SYSTEM_INFO_u([0]);`

but the compiler is not happy:

`error[E0603]: tuple struct SYSTEM_INFO_u is private`

**Comment by retep998** [comment]
That is a union, and the internals are intentionally private so that I can change it to use the union language feature in a future version. [The FAQ covers how to instantiate unions.](https://github.com/retep998/winapi-rs#how-do-i-create-an-instance-of-a-union)
