### ISSUE TITLE
Mark return values of RIDL generated methods as #[must_use]

### ISSUE THREAD

**Issue by smmalis37** [retep998/winapi-rs#573]
Since Windows' HRESULT is an error code, any return values that are HRESULTs should be considered #[must_use] so that you don't forget to check for any error values.

**Comment by retep998** [comment]
I cannot mark `HRESULT` because it is just a typedef to a primitive integer type. Marking the methods themselves is still unstable (https://github.com/rust-lang/rust/issues/43302). There's nothing I can do at the moment.

**Comment by smmalis37** [comment]
Could you change HRESULT to be a wrapper around the int that is marked #[must_use] and Derefs to the int? That should preserve all current functionality i think.

**Comment by retep998** [comment]
That would be a breaking change requiring a new major version, plus it would also require `#[repr(transparent)]` in order to not mess up the ABI (primitives are passed differently than aggregates when calling functions) which is also still unstable (https://github.com/rust-lang/rust/issues/43036).

**Comment by smmalis37** [comment]
Good points. Guess I'll have to wait for #[must_use] on methods. Thanks!
