### ISSUE TITLE
Could not find `wincon` in `um`

### ISSUE THREAD

**Issue by Readarmon0** [retep998/winapi-rs#575]
[https://www.codeproject.com/tips/1053658/win-gui-programming-in-rust-language](url)

I was modernizing the above link's example code now that kernel32 and user32's utilities have essentially been assimilated into winapi-rs. I was able to iron out the wrinkles with the exception of one.

> error[E0433]: failed to resolve. Could not find `wincon` in `um`
   --> src\main.rs:146:21
    |
146 |         winapi::um::wincon::GetConsoleWindow()
    |                     ^^^^^^ Could not find `wincon` in `um`
error: aborting due to previous error

**Comment by retep998** [comment]
Did you remember to enable the relevant features? https://github.com/retep998/winapi-rs#why-am-i-getting-errors-about-unresolved-imports

**Comment by Readarmon0** [comment]
Ah, I knew I was overlooking something. Thanks a bunch. Carry on.
