### ISSUE TITLE
Accessing hardware info (using WMI?)

### ISSUE THREAD

**Issue by mark-summerfield** [retep998/winapi-rs#581]
I'd like to be able to access some hardware info. Normally I use WMI, but actually all I care about is reliably getting the Win32_BaseBoard's properties (e.g., SerialNumber, SKU, etc.) and the Win32_Processor's properties (e.g., ProcessorID, UniqueID, Version, etc.).

Is this possible with winapi-rs as it stands? Any links or help would be appreciated.

**Comment by retep998** [comment]
You would likely have to go through https://msdn.microsoft.com/en-us/library/aa389276(v=vs.85).aspx which I believe isn't bound yet in `winapi` although it certainly could be in the future.
