### ISSUE TITLE
winapi km

### ISSUE THREAD

**Issue by kgv** [retep998/winapi-rs#605]
@retep998 
Are there any plans to add `km`?
Maybe need some help with this?

`km` documentation:
* https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_kernel/
* https://github.com/MicrosoftDocs/windows-driver-docs-ddi

relative: #541

**Comment by woodgear** [comment]
https://github.com/Trantect/winapi-rs/tree/feature/km

**Comment by woodgear** [comment]
https://github.com/retep998/winapi-rs/pull/757
