### ISSUE TITLE
no `shellapi` in `um`

### ISSUE THREAD

**Issue by sailfish009** [retep998/winapi-rs#615]
i am using msys2 64bit rust nightly version:

https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/shellapi/index.html

```
extern crate winapi;
use winapi::um::shellapi as shell;

 --> src\main.rs:41:5
   |
41 | use winapi::um::shellapi as shell;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `shellapi` in `um`

```

**Comment by retep998** [comment]
To quote the `README`:

> ### Why am I getting errors about unresolved imports?
>
> Each module is gated on a feature flag, so you must enable the appropriate feature to gain access to those items. For example, if you want to use something from `winapi::um::winuser` you must enable the `winuser` feature.

**Comment by sailfish009** [comment]
Thanks,

vim Cargo.toml

```
[dependencies]
winapi={version = "0.3.4", features = ["winuser", "shellapi"]}
```
