### ISSUE TITLE
RegCreateKey functions should return LONG

### ISSUE THREAD

**Issue by lem0nify** [retep998/winapi-rs#620]
RegCreateKey functions ([RegCreateKeyA](https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/winreg/fn.RegCreateKeyA.html), [RegCreateKeyW](https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/winreg/fn.RegCreateKeyW.html)) in your library don't return any value but it's wrong.

[As documented in MSDN](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms724842(v=vs.85).aspx), they have to return LONG.

**Comment by retep998** [comment]
According to the headers they actually return `LSTATUS` (which is just a typedef to `LONG`). Thanks for catching this, I'll push out a fix shortly.
