### ISSUE TITLE
Native Wifi / Wlanapi

### ISSUE THREAD

**Issue by petsuter** [retep998/winapi-rs#624]
[MSDN Native Wifi Reference](https://msdn.microsoft.com/en-us/library/windows/desktop/ms706275(v=vs.85).aspx) -> `Wlanapi.h` etc.

Is this missing and wanted?

**Comment by retep998** [comment]
Is it missing? Yes.
Is it wanted? I don't know who wants it, but I am assuming that you probably want it given that you filed this issue.

**Comment by dabernado** [comment]
If y'all will allow me to chime in, I would love to have this implemented.

I am currently writing an application that aims to use Wifi Direct. I'm willing to contribute some code as needed, though I'm somewhat of a Rust n00b and haven't wrote Windows FFI bindings in Rust before.

**Comment by hardliner66** [comment]
@retep998 I want it too. I'm currently evaluating rust as an replacement for an old codebase which makes heavy use of the wlan api.
