### ISSUE TITLE
IDropTarget, RegisterDragDrop, & RevokeDragDrop

### ISSUE THREAD

**Issue by dannyfritz** [retep998/winapi-rs#628]
Continuing where #627 left off.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms679679(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms678405(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms692643(v=vs.85).aspx

In order to get file drag events in https://github.com/tomaka/winit/issues/448.

**Comment by retep998** [comment]
Fixed by https://github.com/retep998/winapi-rs/pull/631
