### ISSUE TITLE
Struct winapi::um::wincon::CHAR_INFO 

### ISSUE THREAD

**Issue by pabloordonez** [retep998/winapi-rs#646]
This is more of a question than an issue, but something that is making a straightforward code into something cumbersome. The `CHAR_INFO` structure requires an attribute word (colors) and then the char. How can I access the `UnicodeChar` when constructing the struct? I have to map from a vector of os agnostic structure to a CHAR_INFO vector in order to use `WriteConsoleOutputW`.

I prefer not to do a loop by hand creating one by one and then calling the methods if possible. Right now i'm using transmute to map from a `char`.

Thank you in advance, and amazing work migrating all these libraries!

**Comment by retep998** [comment]
Are you not able to do `.map(|attr, ch| let mut ci: CHAR_INFO = mem::zeroed(); ci.Attributes = attr; *ci.Char.UnicodeChar_mut() = ch; ci)`? Transmuting from a `char` is wrong because `char` is a 32-bit unicode scalar value while `UnicodeChar` is a WTF-16 codeunit.

**Comment by pabloordonez** [comment]
Excellent! Yes, that worked. The macros make hard to understand how to work with the unions. There is some documentation in the guidelines, but seeing it now makes sence. I made the change and worked like a charm:
![image](https://user-images.githubusercontent.com/19977695/43325419-fee8e138-918c-11e8-8a68-0c17c4da907c.png)

The code now looks like:
```rust
let char_info_array = cell_buffer
            .iter()
            .map(|cell: &Cell| unsafe {
                let mut char_info: CHAR_INFO = zeroed();
                char_info.Attributes =
                    get_foreground_color(cell.foreground) | get_background_color(cell.background);
                *char_info.Char.UnicodeChar_mut() = cell.character as u16;
                char_info
            })
            .collect::<Vec<CHAR_INFO>>();
```
Here is the code: [terminal.rs](https://github.com/pabloordonez/rustlike/blob/1498e97a91df24bbddceabf0c9f1219a03582bb6/src/windows/terminal.rs#L163-L172)

This is just my first test project with rust, to practice some concepts, while doing something fun. 
Thanks again @retep998  for your help and your work with this library.

**Comment by pabloordonez** [comment]
@retep998 Your suggestion was what i needed. Should i close the question, or are you keeping open for others to read?

**Comment by retep998** [comment]
People can still read issues when they're closed and your issue was solved.

**Comment by pabloordonez** [comment]
Excellent, just to make sure.
