### ISSUE TITLE
add support for AArch64 Windows, MSVC ABI

### ISSUE THREAD

**Issue by froydnj** [retep998/winapi-rs#659]
I'm working on bringing up Firefox on AArch64 Windows.  As part of that effort, @alexcrichton has thrown together a rustc branch targeting `aarch64-pc-windows-msvc` that he plans to submit to upstream Rust soonish.  In parallel with that, I'd like to start adding various conditionals for AArch64 support in `winapi-rs`.

The initial effort is at froydnj/winapi-rs@7ce5d93, though I believe I still have some types to add from `winnt.h`.

I am not planning on adding support for the GNU ABI; that can be a separate project.  I'm not even sure if the mingw project even *has* AArch64 support yet!

**Comment by retep998** [comment]
Adding support for ARM has always been a future goal for winapi, but not something I ever pursued as I don't have a Windows ARM device, nor has anyone ever expressed interest in it before.

**Comment by retep998** [comment]
There is now aarch64 support in the repo and it is tested somewhat on CI.
