### ISSUE TITLE
Rust warning: crate names soon cannot contain hyphens: advapi32-sys

### ISSUE THREAD

**Issue by bozaro** [retep998/winapi-rs#67]
http://internals.rust-lang.org/t/pre-rfc-resolve-support-for-hyphens-in-crate-names/1459

**Comment by tomaka** [comment]
Package names can still contain hyphens.

**Comment by bozaro** [comment]
I fix local compilation errors by replacing strings like:
```extern crate "winmm-sys" as winmm;```
to
```extern crate winmm_sys as winmm;```

**Comment by retep998** [comment]
I'm going to rename the crates themselves to remove the sys prefix while leaving it in the package name.

**Comment by retep998** [comment]
Fixed
