### ISSUE TITLE
Question: Enum with a signed negative variant

### ISSUE THREAD

**Issue by mattlknight** [retep998/winapi-rs#673]
I'm very new to public contributing, but I would like to help move this project forward, especially in regards to iphlpapi.h and related.

In shared/tcpestats.h, there is an enum called _TCP_BOOLEAN_OPTIONAL that has a variant TcpBoolOptUnchange = -1. It appears the provided macro ENUM! only handles u32.

I'm either approaching this wrong, in regards to signed enum variants, or I need help understanding how to write the non-macro enum in rust.

Can someone help me understand how to best approach this?

**Comment by retep998** [comment]
https://github.com/retep998/winapi-rs/blob/dev/CONTRIBUTING.md#constants

>If the constant has an unsigned type, but the literal needs to be negative, perform a cast such as -1i16 as u16. Use the primitive integer types that correspond to the type of the constant.

Therefore: `-1i32 as u32`

**Comment by mattlknight** [comment]
@retep998 Thank you very much for the quick response! So, just to confirm, that would cause an underflow of the unsigned value and wrap to maximum minus 1. Are there negative consequences/side-effects for the caller expecting a negative 1 and instead getting a high range positive value?

Enum that I am porting to rust, forgot to include it in initial post.
```c
//
// TCP_BOOLEAN_OPTIONAL
//
// Define the states that a caller can specify when updating a boolean field.
//

typedef enum _TCP_BOOLEAN_OPTIONAL {
    TcpBoolOptDisabled = 0,
    TcpBoolOptEnabled,
    TcpBoolOptUnchanged = -1
} TCP_BOOLEAN_OPTIONAL, *PTCP_BOOLEAN_OPTIONAL;
```

So this would be the correct code then? (It does already pass tests)
```rust
ENUM!{enum TCP_BOOLEAN_OPTIONAL {
    TcpBoolOptDisabled = 0,
    TcpBoolOptEnabled,
    TcpBoolOptUnchanged = -1i32 as u32,
}}
pub type PTCP_BOOLEAN_OPTIONAL = *mut TCP_BOOLEAN_OPTIONAL;
```

Thank you again for all of the help! I want to contribute, but I don't want to do it poorly. :) I read the CONTRIBUTING guide several times, I can't believe I missed that part.

**Comment by retep998** [comment]
The bit pattern is identical regardless of whether it is -1 or 4294967295, and since you'll never be doing calculations with that value, but rather just storing it in struct fields and passing it to functions, whether it is technically -1 or 4294967295 is irrelevant as Windows API will interpret it correctly.

And yes, that would be the correct code.

**Comment by mattlknight** [comment]
That makes perfect sense. Thank you for the help @retep998 ! I will close this issue now.
