### ISSUE TITLE
Question: How do I properly use BITFIELD! contained within a UNION! ?

### ISSUE THREAD

**Issue by mattlknight** [retep998/winapi-rs#674]
I am trying to figure out how to finish out iphlpapi.h and related files. In shared/ifdef.h there is a union that has a struct with bitfields in it. This is causing me some grief as I am very noob, both with public contributing and C/FFI.

Here is the block from ifdef.h:
```c
typedef union _NET_LUID_LH
{
    ULONG64     Value;
    struct
    {
        ULONG64     Reserved:24;
        ULONG64     NetLuidIndex:24;
        ULONG64     IfType:16;                  // equal to IANA IF type
    }Info;
} NET_LUID_LH, *PNET_LUID_LH;
```

Here is what I am trying to do in rust:
```rust
UNION!{union NET_LUID_LH {
    [u64; 1],
    Value Value_mut: ULONG64,
    Info Info_mut: ULONG64,
}}

BITFIELD!{NET_LUID_LH Info: ULONG64 [
    Reserved set_Reserved[0..24],
    NetLuidIndex set_NetLuidIndex[24..48],
    IfType set_IfType[48..64],
]}
```

The issue is, the compiler complains about using "Info" as a value instead of calling it as a method. When I look at the UNION macro code, (I can barely understand macros), it looks like each field is turned into a method. So to access the "Info" field on the union, it would technically be calling a method, if I understand correctly. However, I can't call Info() within the BITFIELD macro as it doesn't expect those characters.

Here is the error message in rust, which appears to be the result of the macro
```rust
error[E0615]: attempted to take value of method `Info` on type `&mut shared::ifdef::NET_LUID_LH`
  --> src\shared\ifdef.rs:76:23
   |
76 | BITFIELD!{NET_LUID_LH Info: ULONG64 [
   |                       ^^^^
   |
   = help: maybe a `()` to call it is missing?
```

Can someone help me understand how to properly write this?

EDIT: Atteched Error output from cargo

**Comment by mattlknight** [comment]
I think I may have figured out the correct way to do it. I've been taking a new look at this and comparing it to existing usage of UNIONs and BITFIELDs.

This is what I have come up with and so far seems to test OK.
```rust
STRUCT!{struct NET_LUID_LH_s {
    bitfield: ULONG64,
}}
BITFIELD!{NET_LUID_LH_s bitfield: ULONG64 [
    Reserved set_Reserved[0..24],
    NetLuidIndex set_NetLuidIndex[24..48],
    IfType set_IfType[48..64],
]}
UNION!{union NET_LUID_LH {
    [u64; 1],
    Value Value_mut: ULONG64,
    Info Info_mut: NET_LUID_LH_s,
}}
pub type PNET_LUID_LH = *mut NET_LUID_LH;
```

From original C source:
```c
typedef union _NET_LUID_LH
{
    ULONG64     Value;
    struct
    {
        ULONG64     Reserved:24;
        ULONG64     NetLuidIndex:24;
        ULONG64     IfType:16;                  // equal to IANA IF type
    }Info;
} NET_LUID_LH, *PNET_LUID_LH;
```

Can someone confirm if that looks correct?

**Comment by retep998** [comment]
Rename `NET_LUID_LH_s` to `NET_LUID_LH_Info` and then it'll be good.

**Comment by mattlknight** [comment]
Awesome! That was a bit of a learning curve for me. Thank you for the help @retep998 !
