### ISSUE TITLE
Question: Handling of #define SIZEOF_X Functions

### ISSUE THREAD

**Issue by mattlknight** [retep998/winapi-rs#676]
I'm still very new to C and FFI, as well as this project. Are we supposed to be adding in the rust equivalent for the #DEFINE functions that provide a size_of return value?

For example, this is a define in ifmib.h
```c
#define SIZEOF_IFTABLE(X) (FIELD_OFFSET(MIB_IFTABLE,table[0]) + \
                           ((X) * sizeof(MIB_IFROW)) + ALIGN_SIZE)
```

The full block is this:
```c
typedef struct _MIB_IFTABLE {
    DWORD dwNumEntries;
    MIB_IFROW table[ANY_SIZE];
} MIB_IFTABLE, *PMIB_IFTABLE;

#define SIZEOF_IFTABLE(X) (FIELD_OFFSET(MIB_IFTABLE,table[0]) + \
                           ((X) * sizeof(MIB_IFROW)) + ALIGN_SIZE)
```

I don't really understand if I should be defining some sort of function to return the value that SIZEOF_IFTABLE(Z) would, or if I should be calculating it in advance and storing it as a pub const number.

Can someone provide some input on this? If I am supposed to be defining this, can you provide/point me to an example?

Thanks,
Matt

**Comment by retep998** [comment]
Just leave a FIXME with that commented out. While `size_of` is already a nuisance due to not being a const function yet, the bigger hurdle is `FIELD_OFFSET` which requires `offset_of` which doesn't exactly exist yet.

**Comment by mattlknight** [comment]
Thanks will do!

**Comment by Inc0n** [comment]
Hi, I am fairly new to rust, and trying to find std::mem::size_of in place of c's sizeof on PROCESSENTRY32,
but it's complaining mismatched type
```
error[E0308]: mismatched types  
  |  
  |   procEntry.dwSize = std::mem::size_of::<PROCESSENTRY32>(); 
  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32,  found usize  
```

How do i fix this? 
Thanks in advance

**Comment by retep998** [comment]
Rust does not do implicit numeric conversions unlike C so you have to cast the type.
`procEntry.dwSize = std::mem::size_of::<PROCESSENTRY32>() as DWORD;`

**Comment by Inc0n** [comment]
ah, thanks, that fix it for me 😅
