### ISSUE TITLE
Line tests

### ISSUE THREAD

**Issue by MSxDOS** [retep998/winapi-rs#682]
@retep998  I'm curious, where are there no tests for blank\too long lines in src ? I noticed you merged #665 unchanged, are you going to fix this one later on or this is no longer relevant? If it is, do you one _someone_ to add the tests (and fix everything that arises) ?

**Comment by retep998** [comment]
For that PR specifically I'm going to add newlines myself later, because it would be too complicated to get it right through the review cycle. There isn't much of a need for a test, as I can find all the offending lines with a trivial `^.{100,}$` ripgrep and fix them easily.
