### ISSUE TITLE
Why is DwmDefWindowProc a typedef and not a function? How to call it?

### ISSUE THREAD

**Issue by fschutt** [retep998/winapi-rs#685]
For implementing hit-testing in non-client window areas, the Microsoft docs say to call `DwmDefWindowProc`, so that the DWM can do it's hit-testing for the "close, maximize, minimize" buttons. I'm trying something like https://stackoverflow.com/a/41111488/5317180 with winit.

However, I don't know how I could call `DwmDefWindowProc ` because it is merely a typedef over an `Option<extern fn>` - I tried:

```rust
if let Some(dwm_def_window_proc) = DwmDefWindowProc  {
    let mut hit_test_non_client_area: LRESULT = unsafe { mem::zeroed() };
    if unsafe { wndproc(window, msg, wparam, lparam, &hit_test_non_client_area) } == 0 {
          println!("Close, maximize or minimize button was hit!");
          hit_test_non_client_area
    } else {
          0
    }
}
```

... but this doesn't work as rustc complains `expected value, found type alias`. So I can't get the callback out of the Option - how can I access `DwmDefWindowProc` and call it?

Why is `DwmDefWindowProc` an Option in the first place? - if it has to do something with dynamic loading, can't there just be a function `load_dwm_def_window_proc()` that returns an `Option<extern fn>` - how am I supposed to call this function?

**Comment by fschutt** [comment]
Here seems to be the definition: https://github.com/retep998/winapi-rs/blob/0.3/src/um/dwmapi.rs#L140-L146 - why is it wrapped in a `FN!` macro instead of just being an `extern fn` like all the other functions?

**Comment by retep998** [comment]
I blame @MSxDOS writing that and myself for not catching that during review. In the headers it is a normal extern function, so I'll have to fix that.

**Comment by MSxDOS** [comment]
@retep998 seems that like me you got mislead by the word `Proc` in its name. 
Kinda embarrassing considering how trivial it is to distinguish an extern function from a function pointer typedef  :smile:
