### ISSUE TITLE
PlaySoundW does not accept string in first parameter

### ISSUE THREAD

**Issue by flip111** [retep998/winapi-rs#691]
https://msdn.microsoft.com/ru-ru/library/windows/desktop/dd743680(v=vs.85).aspx

```
pszSound
A string that specifies the sound to play. The maximum length, including the null terminator, is 256 characters.
```

rust error
```
PlaySoundW("test.wav", null(), SND_FILENAME | SND_SENTRY | SND_SYNC);
           ^^^^^^^^^^ expected u16, found str

   = note: expected type `*const u16`
              found type `&'static str`
```

my friend who programs in C++ says there it's possible to do something like

```c++
PlaySound("C:\\Users\\Commander\\Desktop\\test1.wav", NULL, SND_FILENAME | SND_SYNC);
```

**Comment by flip111** [comment]
So i realize what the issue is here (similar to https://github.com/retep998/winapi-rs/issues/690), but let's talk about the ergonomics of this function. Perhaps it's possible to add a macro to winapi that converts string literal of type &str to https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/winnt/type.LPCWSTR.html on compile time?

**Comment by iancormac84** [comment]
Hello @flip111 . The convention seems to be that winapi-rs provides raw functions and data types as they are, and the user of these functions provides the ergonomic APIs that wrap these functions. Here is an [incomplete example on how to do so](https://gist.github.com/iancormac84/4265a8f61ec59a8852c143da60fb6394). Using this method of making the string type generic with the AsRef<OsStr> declaration allows the user to input a wide variety of Rust string types.

**Comment by flip111** [comment]
Hi @iancormac84 thanks for your code. I also found this thread which contains some interesting code https://www.reddit.com/r/rust/comments/37k1ij/converting_str_to_utf16/

I will look at both codes and get back to you. All the code so far seem to be runtime though, but i could be mistaken. Ideally for string literals it should be on compile time.

For this library in specific i suggest to add a macro and also documentation on how to deal with this. I think pointing to MSDN is not enough because there is a gap between using a string literal in c++ and rust doesn't work 1 on 1. This is expected looking by the types, but please let's close this gap with some documentation and possibly the macro.

**Comment by iancormac84** [comment]
Understood!

**Comment by retep998** [comment]
The example in the readme already demonstrates how to convert a Rust string into a wide string: `let wide: Vec<u16> = OsStr::new(msg).encode_wide().chain(once(0)).collect();`

If you want something more ergonomic there exists https://github.com/retep998/wio-rs/blob/master/src/wide.rs

`winapi` itself cannot provide such conversion facilities directly as it tries to support `no_std` scenarios, which means it cannot rely on the functionality in `std` to do so. Also doing so at *compile* time is even harder because that requires procedural macros.

**Comment by flip111** [comment]
Quote from IRC:

> Doing Rust string to wide string conversions at compile time requires a procedural macro. And procedural macros are hella complicated

i will pray for wio-rs 😆
