### ISSUE TITLE
Add support for the new ConPTY API

### ISSUE THREAD

**Issue by zacps** [retep998/winapi-rs#695]
The API allows for communicating with CLI processes without passing through cmd.

~~It's currently only available on insider builds~~ and is only documented (as far as I can tell) in [this blog post](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/).

I'm not sure what the policies for dealing with insider APIs is, but this would be very useful for the implementation of the API in alacritty. See the [downstream issue](https://github.com/zacps/alacritty/issues/25).

**Comment by retep998** [comment]
I generally prefer to wait until there is a stable Windows SDK release with the definitions.

**Comment by zacps** [comment]
Yeah I thought that might be the case but couldn't find any issues about it.

Mind keeping this open until it gets stabilised?

**Comment by cloudhan** [comment]
@zacps maybe make you own binding and let @retep998 "Embrace, extend, and extinguish" your crate finally

**Comment by yrp604** [comment]
These functions are included in the 10.0.17763.0 release of the Win 10 SDK

**Comment by zacps** [comment]
More concretely, this is available on 1809 under the `Semi-Annual (Targeted)` channel.

The new functions are also documented [here](https://docs.microsoft.com/en-us/windows/console/console-functions).

**Comment by Rican7** [comment]
The APIs are included in Windows 10 v1809 (10.0.17763) release of the Windows 10 SDK, which was released in October 2018, and is currently "generally available".

 - https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk
 - https://docs.microsoft.com/en-us/windows/console/createpseudoconsole#requirements
