### ISSUE TITLE
Question: Where can I find GMEM_MOVEABLE?

### ISSUE THREAD

**Issue by sru** [retep998/winapi-rs#707]
Hello,

I am trying to allocate memory using `GlobalAlloc`.
I want to pass data to clipboard, and the MSDN documentation says I need to use `GlobalAlloc`.
One of the things I need to do is to pass `GMEM_MOVEABLE` into `GlobalAlloc`.

I only found [a comment `GMEM_*` in the source code](https://github.com/retep998/winapi-rs/blob/3792048cb07f9b762f8f0913293027759ea78db2/src/um/winbase.rs#L226).

Relevant flags are missing as well:
- GHND
- GPTR
- GMEM_FIXED
- GMEM_MOVEABLE
- GMEM_ZEROINIT

And obsolete flags:

- GMEM_DDESHARE
- GMEM_DISCARDABLE
- GMEM_LOWER
- GMEM_NOCOMPACT
- GMEM_NODISCARD
- GMEM_NOT_BANKED
- GMEM_NOTIFY
- GMEM_SHARE

Which, I found in [MSDN documentation](https://docs.microsoft.com/en-us/windows/desktop/api/WinBase/nf-winbase-globalalloc).

I could find `LocalAlloc` counterparts (`LHND`, `LPTR`, `LMEM_MOVEABLE`, etc.) [here](https://github.com/retep998/winapi-rs/blob/fa4e2c5a6dc495c71e6031bdde2e52870ebf6fdf/src/um/minwinbase.rs#L318).

Are these simply overlooked or not implemented yet? Do I need to look at different crate?

Thanks.

**Comment by retep998** [comment]
This is the correct crate. They're just not implemented yet.
