### ISSUE TITLE
Missing Helper Structures for D3D12

### ISSUE THREAD

**Issue by Joseph-LeGrice** [retep998/winapi-rs#721]
The structures listed here: https://docs.microsoft.com/en-us/windows/desktop/direct3d12/helper-structures-for-d3d12 appear to be missing. Any particular reason for this? Happy to help out adding them if wanted/needed.

**Comment by retep998** [comment]
I don't see see these definitions in any of the Windows SDK headers.

**Comment by Joseph-LeGrice** [comment]
Ah yes, sorry. Appears that they are part of a separate helper library. Thanks for having a quick look.

**Comment by MichaelMauderer** [comment]
Just ran into he same thing. Some MS tutorial included calls to helper functions from this library. 
Might be good to explain the workaround for people stumbling across this issue.
Is there another crate wrapping these?
