### ISSUE TITLE
Missing InitiateShutdown calls in winreg 

### ISSUE THREAD

**Issue by lamogui** [retep998/winapi-rs#723]
I saw they are commented... any reason for this ?
See https://docs.microsoft.com/en-us/windows/desktop/api/Winreg/nf-winreg-initiateshutdowna

**Comment by freshstrangemusic** [comment]
The `InitiateSystemShutdownEx{A,W}` methods are also missing. See [msdn](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-initiatesystemshutdownexa)

**Comment by commonsensesoftware** [comment]
Sorry to rehash a closed issue. I see many missing Registry APIs were added in September 2019, but the last release is August 2019. Unless I'm missing something, there is no published crate that has these APIs in it. I specifically need **RegLoadAppKeyA** to create _Application Hives_ for testing. Is there some other reason to hold up a `0.3.10` release? It would seem there is a `0.4.0` in the works as well. Is there are recommendation to bridge the gap until latest changes tothe `0.3` branch are released?

Thanks
