### ISSUE TITLE
IBackgroundCopyJobHttpOptions has the wrong uuid

### ISSUE THREAD

**Issue by hcs64** [retep998/winapi-rs#736]
https://github.com/retep998/winapi-rs/blob/6a9df5f3e7d1c98bf6cd48c0bf334367450a122f/src/um/bits2_5.rs#L23

Based on my 10.0.15063.0 `bits2_5.h`, this should be `f1bd1079-9f01-4bdc-8036-f09b70095066`. `83E81B93-0873-474D-8A8C-F2018B1A939C` is the IID of `IBackgroundCopyFile2`, which is correct in `bits2_0.rs`.

This seems to work locally:

    RIDL! {#[uuid(0xf1bd1079, 0x9f01, 0x4bdc, 0x80, 0x36, 0xf0, 0x9b, 0x70, 0x09, 0x50, 0x66)]

**Comment by retep998** [comment]
Fixed by https://github.com/retep998/winapi-rs/pull/737
