### ISSUE TITLE
EnumWindows‘s callback's LPARAM should be a reference.

### ISSUE THREAD

**Issue by aurexav** [retep998/winapi-rs#746]
C code:

```
BOOL CALLBACK EnumWindowsProc(HWND hwnd, LPARAM lParam)
{
    char buffer[128];
    int written = GetWindowTextA(hwnd, buffer, 128);
    if (written && strstr(buffer,"Mozilla Firefox") != NULL) {
        *(HWND*)lParam = hwnd;
        return FALSE;
    }
    return TRUE;
}

HWND GetFirefoxHwnd()
{
    HWND hWnd = NULL;
    EnumWindows(EnumWindowsProc, &hWnd);
    return hWnd;
}
```

So we can get the `hwnd` from `lParam`.

But in Rust version, we can't get it out of `enum_windows_proc` function.

**Comment by retep998** [comment]
C has a lot of implicit conversions that Rust does not do, so you just have to do them explicitly like so:

`EnumWindows(EnumWindowsProc, &mut hWnd as *mut HWND as LPARAM);`
`*(lParam as *mut HWND) = hwnd;`

**Comment by aurexav** [comment]
@retep998  I try `*(l_param as *mut HWND) = hwnd;` but get: **process didn't exit successfully (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)**

```rust
fn find_window() -> Result<HWND, Error> {
    // --- external ---
    use winapi::{
        shared::minwindef::LPARAM,
        um::{
            winnt::LPWSTR,
            winuser::{EnumWindows, FindWindowW},
        },
    };

    extern "system" fn enum_windows_proc(hwnd: HWND, l_param: LPARAM) -> i32 {
        // --- std ---
        use std::{
            alloc::{Layout, alloc, dealloc},
            ffi::OsString,
            os::windows::ffi::OsStringExt,
            slice::from_raw_parts,
        };
        // --- external ---
        use winapi::um::winuser::GetWindowTextW;

        unsafe {
            let capacity = 128;
            let layout = Layout::from_size_align_unchecked(capacity, 8);
            let ptr = alloc(layout);
            let lp_string = ptr as LPWSTR;

            GetWindowTextW(hwnd, lp_string, capacity as i32);

            let name = OsString::from_wide(from_raw_parts(
                lp_string,
                {
                    let mut len = 0;
                    for i in 0..capacity as isize { if *(lp_string).offset(i) != 0 { len += 1; } else { break; } }

                    len
                },
            ));

            dealloc(ptr, layout);

            if name.to_str().unwrap() == "xxx" {
                *(l_param as *mut HWND) = hwnd;
                0
            } else { 1 }
        }
    }

    unsafe {
        let mut hwnd = FindWindowW(
            0 as LPWSTR,
            "something else to enter hwnd.is_null()".encode_utf16()
                .collect::<Vec<u16>>()
                .as_ptr(),
        );

        if hwnd.is_null() {
            EnumWindows(Some(enum_windows_proc), &mut hwnd as *mut HWND as LPARAM);
            Err(Error::FindWindowError)
        } else { Ok(hwnd) }
    }
}
```

**Comment by retep998** [comment]
The capacity you are specifying in `Layout` is in terms of bytes, but when you pass the same capacity to `GetWindowTextW` it is interpreting it as the number of wchars, so it could potentially be writing into invalid memory. There's no need to be manually allocating memory like that anyway, and you should probably just use a `[u16; 128]` on the stack. Also the string you are passing to `FindWindowW` is not nul terminated so it is reading invalid memory.

**Comment by aurexav** [comment]
Thanks, I will correct those problems. But if I comment `EnumWindows(Some(enum_windows_proc), &mut hwnd as *mut HWND as LPARAM);` it works as my expectation (return Error). Maybe something wrong with `hwnd`?

**Comment by retep998** [comment]
I cleaned up your callback and now it works correctly for me.
```rust
        unsafe {
            let mut buf = [0; 128];
            let len = GetWindowTextW(hwnd, buf.as_mut_ptr(), buf.len() as i32);
            let name = OsString::from_wide(&buf[..len as usize]);
            if name.to_str().unwrap() == "xxx" {
                *(l_param as *mut HWND) = hwnd;
                0
            } else { 1 }
        }
```

**Comment by aurexav** [comment]
Works!

**Comment by aurexav** [comment]
There's one more thing confuse me.
What's the different between `let mut buf = [0; 128]` and `let mut buf = Vec::with_capacity(128)`?

- `let mut buf = [0; 128]`, when I print `buf.to_vec()` it shows some data.
-  `let mut buf = Vec::with_capacity(128)`, when I print `buf` it shows empty `Vec`.

**Comment by retep998** [comment]
`Vec::with_capacity(128)` will heap allocate memory, but it won't actually fill any values in and the length will remain 0. Also `[0; 128]` creates an array on the stack without heap allocating, and its heap allocating equivalent would be `vec![0; 128]`.

**Comment by aurexav** [comment]
I can use `let buf = std::slice::from_raw_parts(vec_buf_ptr, len)` get the slice, does the data take up the `with_capacity(128)`? If yes, when I push something into `vec_buf` what will happen. If not, where is the data to be stored?

**Comment by retep998** [comment]
If you do `std::slice::from_raw_parts(some_vec.as_ptr(), some_vec.capacity())` to get a slice of that `Vec` you will have caused undefined behavior because you created a slice to uninitialized memory. All the data between `.capacity()` and `.len()` is uninitialized. The first time you push something into the `Vec` it will write that value into the first slot in that memory block and increase the `.len()` by one.

**Comment by aurexav** [comment]
Really really appreciate your help!
