### ISSUE TITLE
Example on using COM interface

### ISSUE THREAD

**Issue by MOZGIII** [retep998/winapi-rs#750]
Please add an example of using COM interface to the readme.
Thanks in advance.

My goal is to create a safe wrapper for `IDesktopWallpaper` from #745, and I don't understand how to use the code from that PR, nor where to look it up.
I'm relatively new to Rust, and not an expert in COM nor Windows. I'd like to have a usage example for all the functionality that `winapi-rs` provides. Not necessarily for all the functions (i.e. everything in the crate) - but just a single good example for each of the significantly different case would definitely be a game changer for me.

So far, I can the following things that worth having an example:

- ~using C API (for example stuff from `user32.dll`);~ is already in the README
- using COM API (`shlobj_core`, creation, use and deletion of an interface);
- implementing a COM interface;
- extending `winapi-rs` (aka contribution guide).

Maybe there's something else I don't yet know of.

**Comment by retep998** [comment]
I intend to eventually create a repository full of examples and links to crates that are good examples, and link to it from the readme. I'm not about to add COM examples directly to the readme as it is already long enough as is.

**Comment by MOZGIII** [comment]
Ok, could please hook me us with a link or something here for a quick solution? All I could find in the internet is for v0.2 of winapi-rs. Really looking forward to it.
I know I should somehow create a `IDesktopWallpaper` implementor, probably using `CoInitializeEx` - but I wasn't able to go from than that basic understanding to something concrete.

**Comment by MOZGIII** [comment]
If you know a crate that uses COM API - that'd be enough for me, cause I scrolled over crates.io but couldn't find the one that'd do it.

**Comment by MOZGIII** [comment]
Just fiogured I could use github search: https://github.com/search?p=1&q=CoInitializeEx+language%3Arust&type=Code
