### ISSUE TITLE
A way to reduce winapi-*-pc-windows-gnu?

### ISSUE THREAD

**Issue by RazrFalcon** [retep998/winapi-rs#754]
Currently, they are almost 100MB big, which is a bit of a problem when using `cargo-vendor`.

Is there a way to reduce their size or make them optional?

**Comment by retep998** [comment]
Those import libraries are necessary when targeting `pc-windows-gnu` unfortunately, and there's nothing sane I can *currently* do to improve the situation. However once https://github.com/rust-lang/rust/issues/58713 is implemented I will be able to eliminate them entirely.

**Comment by RazrFalcon** [comment]
I see. Thanks.
