### ISSUE TITLE
how to add a new lib(km) in winapi style?

### ISSUE THREAD

**Issue by woodgear** [retep998/winapi-rs#756]
hi guys.i am currently working on add km binding of winapi , and it almost done.but now i am confuse how should i migrate it to winapi.
# what i have done/how i do now
when we talk about add binding of a windows api , for example [FltStartFiltering](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltstartfiltering) we must add the .lib file (windows import library) to cargo:rustc-link-search=native,the sybmol (what we externed) could be find there.
```rust
    // build.rs
    let target = var("TARGET").unwrap();
    if target.starts_with("x86_64") {
        let dir = var("CARGO_MANIFEST_DIR").unwrap();
        println!("cargo:rustc-link-search=native={}", Path::new(&dir).join("x64").display());
    }
    if target.starts_with("i686") {
        let dir = var("CARGO_MANIFEST_DIR").unwrap();
        println!("cargo:rustc-link-search=native={}", Path::new(&dir).join("x86").display());
    }
```
```
ls kernel-native-lib/x64/
fltMgr.lib  fwpkclnt.lib  ndis.lib  ntoskrnl.lib
```
and then we could write some thing like
```
#[link(name = "fltMgr")]
extern "system" {
    pub fn FltUnregisterFilter(Filter: PFLT_FILTER);
    pub fn FltStartFiltering(Filter: PFLT_FILTER) -> NTSTATUS;
}
```
finally,we could just call FltStartFiltering on rust
# what i confuse
i could not find *.lib file under winapi, just a bunch of *.a file under /lib,where those file from?,what does they mean?what different between it and *.lib file which under Windows Kits\10\Lib\10.0.17763.0\km?
i also notify that there are some *.def file, it seems the  [Export File](https://docs.microsoft.com/en-us/cpp/build/reference/building-an-import-library-and-export-file?view=vs-2019),it seems point the export functions of a lib,but i could not found how it works.
please give me some advice,thanks.

**Comment by retep998** [comment]
The `.def` and `lib*.a` files are for MinGW. Don't worry about them.

There's currently a lot of unresolved questions around how to deal with writing Rust code for kernel mode windows, such as whether it should get its own target, which it really should. At the moment while `winapi` can provide bindings to types and constants from the Windows DDK, it cannot provide bindings to functions.

**Comment by woodgear** [comment]
i have deal the target question (xargo + custom toolchain config)
