### ISSUE TITLE
Signature of StackWalkEx takes LPSTACKFRAME64 instead of LPSTACKFRAME_EX

### ISSUE THREAD

**Issue by alexcrichton** [retep998/winapi-rs#768]
The [`StackWalkEx` function](https://docs.rs/winapi/0.3.7/i686-pc-windows-msvc/winapi/um/dbghelp/fn.StackWalkEx.html) takes the wrong type for its stack frame parameter. The [reference documentation](https://docs.microsoft.com/en-us/windows/desktop/api/dbghelp/nf-dbghelp-stackwalkex) cites it takes `LPSTACKFRAME_EX` but instead winapi is defining it with `LPSTACKFRAME64`

**Comment by retep998** [comment]
Thanks for catching this!
