### ISSUE TITLE
Make it optional to link to opengl32.dll

### ISSUE THREAD

**Issue by paulrouget** [retep998/winapi-rs#773]
As of now, opengl32.dll is linked on non-arm platforms, requiring the presence of OpenGL on the target.

**Comment by retep998** [comment]
If no symbols from `opengl32.lib` are referenced, then there will be no dependency on `opengl32.dll`. For non-arm platforms there should be no need to avoid linking to it. The only issue is with arm platforms where `opengl32.lib` doesn't exist resulting in linker errors and there's already a conditional to avoid `opengl32.lib` on those targets.

**Comment by paulrouget** [comment]
Understood. Thanks.
