### ISSUE TITLE
Plan for the next release? 

### ISSUE THREAD

**Issue by chandde** [retep998/winapi-rs#774]
Hi @retep998 

Looking for a new release to carry the ARM fixes I recently upstreamed (thank you for approving and merging the change!), we have a few other crates that are waiting for this release, so we can update their dependency on winapi to the newer one to be able to compile for Windows ARM32, namely iovec, mio, miow, etc.  Please share your plan on next release so we can plan accordingly. Much appreciated!!

Thanks
Chandler.

**Comment by retep998** [comment]
My plan for each release is to merge a bunch of PRs over an indeterminate period of time, and then spend a few days checking that no reverse dependencies of `winapi` were broken by any recent changes.

**Comment by chandde** [comment]
that sounds like a good plan~~
