### ISSUE TITLE
Link error with DXGIGetDebugInterface

### ISSUE THREAD

**Issue by Kamayuq** [retep998/winapi-rs#800]
DXGIGetDebugInterface seems to be missing 
it can be found in C:\Windows\System32\DXGIDebug.dll

error LNK2019: unresolved external symbol DXGIGetDebugInterface referenced in function

**Comment by retep998** [comment]
That is because `DXGIGetDebugInterface` does not exist in any import libraries so it cannot be resolved. You have to use `GetProcAddress` to load it.

**Comment by Kamayuq** [comment]
I used GetProcAddress that worked but I still could not load the COM-Interface.
And than I just found out that one has to Query the debug interface from the d3d12 device.  I assume DXGIGetDebugInterface  was used in an earlier d3d version.
