### ISSUE TITLE
"Could not find `shared` in `winapi`"

### ISSUE THREAD

**Issue by nic-hartley** [retep998/winapi-rs#803]
To repro:

- Create a new project with e.g. `cargo new`
- Edit the following files:
  - `cargo.toml`:

    ```
    [package]
    name = "rust-dx11-engine"
    version = "0.1.0"
    [dependencies]
    winapi = "0.3.7"
    ```
  - `src/main.rs`
    ```
    extern crate winapi;
    use winapi::shared::*;
    fn main() {}
    ```
- Run `cargo build`. It should fail with an E0432.

`cargo`/`rustc` version: 1.36.0 (latest stable), but happens with nightly too.

There [doesn't seem](https://github.com/retep998/winapi-rs/blob/0.3/src/lib.rs#L27) to be any feature gate on `winapi::shared` itself, just (most of) its contents, so I'm very confused.

This [is breaking other crates](https://crates.io/crates/gfx_device_dx11), by the way.

**Comment by retep998** [comment]
Your repro example builds fine for me.
```
> cargo build
    Updating crates.io index
  Downloaded winapi v0.3.8
   Compiling winapi v0.3.8
   Compiling rust-dx11-engine v0.1.0 (...)
warning: unused import: `winapi::shared::*`
 --> src\main.rs:2:5
  |
2 | use winapi::shared::*;
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 5.12s
```
