### ISSUE TITLE
CallNtPowerInformation, parameter mutation by function?

### ISSUE THREAD

**Issue by remingtonc** [retep998/winapi-rs#808]
Hi, thank you for this library. Very useful. Context: First time using Rust, first time using Windows SDKs. Apologies if this is extremely basic, I hope it is.

Attempting to get idleness information via [`CallNtPowerInformation`](https://docs.microsoft.com/en-us/windows/win32/api/powerbase/nf-powerbase-callntpowerinformation?redirectedfrom=MSDN). This function (I believe) expects to place information into the [expected structure](https://docs.microsoft.com/en-us/windows/win32/power/system-power-information-str) based on the supplied `POWER_INFORMATION_LEVEL`. I'm having difficulty reconciling how the structures/function calls should look for a struct not defined in winapi, going through FFI, and as a parameter being mutated. Parameter in question is `teststruct` in `CallNtPowerInformation` call. Example:

```rust
    let mut teststruct = SystemPowerInformationStruct {
        MaxIdlenessAllowed: 0,
        Idleness: 0,
        TimeRemaining: 0,
        CoolingMode: 0
    };
    // Fill in struct and get result code
    let result = unsafe {
        CallNtPowerInformation(
            SystemPowerInformation,
            null_mut(),
            0,
            &teststruct,
            size_of::<SystemPowerInformationStruct>() as u32
        )
    };
```
Errors as `types differ in mutability`. Tried several permutations passing `&teststruct`, `&mut teststruct`, ... struggling:
```
expected enum `std::ffi::c_void`, found struct `prevent_sleep::SystemPowerInformationStruct`
expected enum `std::ffi::c_void`, found reference
...
```

If this is not the place for support, please close. I could default back out of Rust for the sake of getting it done, but this is good learning/fun. :)

Repo code:
https://github.com/remingtonc/nosleep/blob/windows/src/main.rs#L10-L43

**Comment by retep998** [comment]
`&mut teststruct as *mut _ as *mut _`

The correct place for support is either on IRC or Discord.

**Comment by remingtonc** [comment]
Thank you for the support and clarification.
