### ISSUE TITLE
Should we unique `c_void`?

### ISSUE THREAD

**Issue by tesuji** [retep998/winapi-rs#826]
There is core and std c_void type: https://doc.rust-lang.org/nightly/core/ffi/enum.c_void.html
Could we replace that in 
https://github.com/retep998/winapi-rs/blob/02f3e37da9ae921aa87196ba3d58c49311504ca0/src/lib.rs#L34-L37

**Comment by retep998** [comment]
If you're asking whether `winapi` could use `c_void` from `core`, that will happen in `winapi` 0.4.

Otherwise, I'm not sure what you're asking.

**Comment by tesuji** [comment]
Thanks. I opened https://github.com/rust-lang/rust/issues/65922 because people
cannot use `std::ffi::c_void` before Rust 1.30.0

**Comment by sollyucko** [comment]
#771
