### ISSUE TITLE
Process32Next: heap corruption after running again

### ISSUE THREAD

**Issue by rupansh** [retep998/winapi-rs#849]
In order to search a process with Process32Next, I run it under a while loop. However, when the loop runs second time, I get STATUS_HEAP_CORRUPTION and the program panics.
I am running the following code: 
```
    pub fn process(&mut self, process_name: &str){
        let h_pid: HANDLE = unsafe { CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0) };
        let proc_name = String::from(process_name);
        let mut proc_entry: PROCESSENTRY32 = PROCESSENTRY32 {
            dwSize: size_of::<PROCESSENTRY32>().try_into().unwrap(),
            cntUsage: 0,
            th32ProcessID: 0,
            th32DefaultHeapID: 0,
            th32ModuleID: 0,
            cntThreads: 0,
            th32ParentProcessID: 0,
            pcPriClassBase: 0,
            dwFlags: 0,
            szExeFile: [0; 260]
        };

        while unsafe { Process32Next(h_pid, &mut proc_entry) } != 0 {
            let mut i8vec = proc_entry.szExeFile.to_vec();
            let u8_vec = unsafe { Vec::from_raw_parts(i8vec.as_mut_ptr() as *mut u8, i8vec.len(), i8vec.capacity()) };
            let cur_proc = String::from_utf8(u8_vec).unwrap();
            if cur_proc.contains(&proc_name) {
                self.dw_pid = proc_entry.th32ProcessID;
                unsafe { CloseHandle(h_pid) };
                self.h_process = unsafe { OpenProcess(PROCESS_ALL_ACCESS, FALSE, self.dw_pid) };
                return
            }
        }

        println!("Couldn't find game!");
        exit(0)
    }
```

**Comment by rupansh** [comment]
Edit: it seems like it randomly works sometimes and sometimes it doesn't!

**Comment by retep998** [comment]
```Rust
let u8_vec = unsafe { Vec::from_raw_parts(i8vec.as_mut_ptr() as *mut u8, i8vec.len(), i8vec.capacity()) };
```

You're constructing a new `Vec` using the same allocation as an existing `Vec` so you now have two `Vec`s claiming to have ownership over the same allocation. When both are dropped you get a double free, resulting in heap corruption. You're also ignoring nul termination of the string. What you should do instead is:

```Rust
let cur_proc = str::from_utf8(&proc_entry.szExeFile).unwrap();
let length = cur_proc.find('\0').unwrap_or(cur_proc.len());
let cur_proc = &cur_proc[..length];
```

**Comment by rupansh** [comment]
> ```rust
> let u8_vec = unsafe { Vec::from_raw_parts(i8vec.as_mut_ptr() as *mut u8, i8vec.len(), i8vec.capacity()) };
> ```
> 
> You're constructing a new `Vec` using the same allocation as an existing `Vec` so you now have two `Vec`s claiming to have ownership over the same allocation. When both are dropped you get a double free, resulting in heap corruption. You're also ignoring nul termination of the string. What you should do instead is:
> 
> ```rust
> let cur_proc = str::from_utf8(&proc_entry.szExeFile).unwrap();
> let length = cur_proc.find('\0').unwrap_or(cur_proc.len());
> let cur_proc = &cur_proc[..length];
> ```

I see! I should've cloned the vector first :P 
Also str::from_utf8 doesn't seem to be working because it expects a slice instead of an array
Shouldn't we be using u8 for szExeFile instead of i8? It makes more sense and it wouldn't require us to convert the i8 array to a u8 array/vector one.

**Comment by retep998** [comment]
Ah right, `char` in C on Windows is signed by default. As convenient as it may be to use `u8` instead of `i8`, the Rust ecosystem is already built around `c_char` being `i8` on Windows and any changes to that would cause massive compatibility issues.

Anyway, to convert from `&[u8]` to `&[i8]` you can do something like this:
```Rust
let cur_proc = str::from_utf8(std::mem::transmute::<&[i8], &[u8]>(&proc_entry.szExeFile)).unwrap();
```

**Comment by rupansh** [comment]
> Ah right, `char` in C on Windows is signed by default. As convenient as it may be to use `u8` instead of `i8`, the Rust ecosystem is already built around `c_char` being `i8` on Windows and any changes to that would cause massive compatibility issues.
> 
> Anyway, to convert from `&[u8]` to `&[i8]` you can do something like this:
> 
> ```rust
> let cur_proc = str::from_utf8(std::mem::transmute::<&[i8], &[u8]>(&proc_entry.szExeFile)).unwrap();
> ```

I see! Thanks for the help!
