### ISSUE TITLE
Direct3D 11 not detected in Microsoft Windows 8.1

### ISSUE THREAD

**Issue by ghost** [retep998/winapi-rs#852]
### Issue

Examples from crates such as `gfx` throw an unrecognised pixel format error. It can be seen that the [Direct3D 11 backend of `gfx`](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/Cargo.toml#L31) relies in `winapi`.

### Reproducing

- In the crate [gfx](http://github.com/gfx-rs/gfx), running `cargo run --bin quad --features dx11` throws an unrecognised pixel format error.
- The host OS is installed from the Microsoft site (Windows 8.1 Single Language). The tool `dxdiag` relates Direct3D 11 is the current DirectX version.
- Some softwares detect Direct3D 11 in the current OS and render with it, including Flash Player.

**Comment by retep998** [comment]
`winapi` is just raw bindings, so are you *sure* that `winapi` is at fault here? If it works on Windows 10 but not Windows 8.1 then it is likely a backwards compatibility issue with `gfx` and not `winapi`.

**Comment by ghost** [comment]
So it might be an unrecognised device pixel format error. Gonna repost there then.
