### ISSUE TITLE
Is IRC channel listed in Readme still accurate?

### ISSUE THREAD

**Issue by atouchet** [retep998/winapi-rs#879]
In the Readme it states:

"Official IRC channel: #winapi on Mozilla IRC"

As far as I know Mozilla IRC has been shut down. Has the winapi channel moved elsewhere?

**Comment by atouchet** [comment]
It also appears to be referenced in: https://github.com/retep998/winapi-rs/blob/0.3/.travis.yml#L37

**Comment by retep998** [comment]
It is not accurate currently.

**Comment by retep998** [comment]
README has been updated. Travis file will go away eventually.
