### ISSUE TITLE
GetModuleHandleExW always gets err 87

### ISSUE THREAD

**Issue by clouduol** [retep998/winapi-rs#894]
I use the flowing code to get current exe HMODULE:
```
let mut hmodule: HMODULE = null_mut::<HINSTANCE__>();
let r = GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, 
	null(), hmodule as *mut HMODULE);
if r == 0 {
	println!("GetModuleHandleExW err: last err= {:?}", GetLastError());
	return;
}
```

But always get 87 error. This error means `ERROR_INVALID_PARAMETER`. But the corresponding c code works well.

OS: `windows 10`
rust version: `rustc 1.45.0-nightly (75e1463c5 2020-05-13)`
compile command:  `cargo build --target=i686-pc-windows-msvc`

How to make it work well?

**Comment by retep998** [comment]
You're casting your `hmodule` pointer instead of passing in a pointer to `hmodule`. Also you don't need to specify the type parameter to `null_mut`.
```Rust
let mut hmodule: HMODULE = null_mut();
let r = GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, 
	null(), &mut hmodule);
if r == 0 {
	println!("GetModuleHandleExW err: last err= {:?}", GetLastError());
	return;
}
```

**Comment by clouduol** [comment]
> You're casting your `hmodule` pointer instead of passing in a pointer to `hmodule`. Also you don't need to specify the type parameter to `null_mut`.
> 
> ```rust
> let mut hmodule: HMODULE = null_mut();
> let r = GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, 
> 	null(), &mut hmodule);
> if r == 0 {
> 	println!("GetModuleHandleExW err: last err= {:?}", GetLastError());
> 	return;
> }
> ```

Now it works well. Thanks a lot!
