### ISSUE TITLE
expected raw pointer `*mut winapi::ctypes::c_void`            found mutable reference `&mut std::ffi::CString`

### ISSUE THREAD

**Issue by zhuxiujia** [retep998/winapi-rs#919]
```rust
  result = GetDIBits(MemDC, hBitmap, 0, screensize.cy as u32, null_mut(), &mut bitInfo, DIB_RGB_COLORS);
    bitInfo.bmiHeader.biCompression = BI_RGB;
    bitInfo.bmiHeader.biPlanes = 1;
    if result != 0 {
        //do something

        let mut buffer:CString;

        //here i can not fetch  buffer, which Type should i  use       ??
        result = GetDIBits(MemDC, hBitmap, 0, screensize.cy as u32, &mut buffer, &mut bitInfo, DIB_RGB_COLORS);
        println!("success");
    }
```
error[E0308]: mismatched types
  --> src\main.rs:85:69
   |
85 |         result = GetDIBits(MemDC, hBitmap, 0, screensize.cy as u32, &mut buffer, &mut bitInfo, DIB_RGB_COLORS);
   |                                                                     ^^^^^^^^^^^ expected enum `winapi::ctypes::c_void`, found struct `std::ffi::CString`
   |
   = note:    expected raw pointer `*mut winapi::ctypes::c_void`
           found mutable reference `&mut std::ffi::CString`

**Comment by zhuxiujia** [comment]
may be you can  gave me Better advice。 now i close this issues
```rust 
 let size: usize = bitInfo.bmiHeader.biSizeImage as usize;
        let mut buffer: Vec<u8>=vec![];
        for _ in 0..size{
            buffer.push(0 as u8);
        }
        let mut slice:*mut [u8]= buffer.as_mut_slice()  as *mut [u8];
        //第二次调用GetDIBits取图片流数据
        result = GetDIBits(MemDC, hBitmap, 0, screensize.cy as u32,  slice as *mut c_void, &mut bitInfo, DIB_RGB_COLORS);

```

**Comment by retep998** [comment]
```Rust
let mut buffer = vec![0u8; size];
let result = GetDIBits(MemDC, hBitmap, 0, screensize.cy as u32, buffer.as_mut_ptr().cast(), &mut bitInfo, DIB_RGB_COLORS);
```

**Comment by zhuxiujia** [comment]
> ```rust
> let mut buffer = vec![0u8; size];
> let result = GetDIBits(MemDC, hBitmap, 0, screensize.cy as u32, buffer.as_mut_ptr().cast(), &mut bitInfo, DIB_RGB_COLORS);
> ```


Great, but GetDIBts returns 0 after multiple calls。
I haven't been able to find it for a long time
