### ISSUE TITLE
BUG  error: failed to run custom build command for `winapi v0.3.9`

### ISSUE THREAD

**Issue by zhuxiujia** [retep998/winapi-rs#926]
rust version:
```
1.45.0
```

error: failed to run custom build command for `winapi v0.3.9`

Caused by:
  could not execute process `D:\RustProject\cf\target\debug\build\winapi-68cc666bcca840ff\build-script-build` (never executed)

Caused by:
  该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。 (os error 216)

**Comment by retep998** [comment]
216 is `ERROR_EXE_MACHINE_TYPE_MISMATCH`. The build script should always match the host architecture of the compiler, so if the compiler is able to run in the first place to build the build script then there's no reason the build script itself shouldn't be able to run... What a bizarre issue.

What I do know however is that this is *not* `winapi`'s fault. `winapi`'s build script just happens to be one of the first things that gets linked and run in most projects so if your toolchain or environment is misconfigured then `winapi` is one of the first to notice.
