### ISSUE TITLE
Cannot correctly interpret LPARAM as required KBDLLHOOKSTRUCT

### ISSUE THREAD

**Issue by duvallj** [retep998/winapi-rs#951]
I am trying to write a program in Rust that will register one of its functions as a callback via the Windows API to receive events. For a WM_KEYBOARD_LL callback, the LPARAM value should be a pointer to a<https://docs.rs/winapi/0.3.9/winapi/um/winuser/struct.KBDLLHOOKSTRUCT.html> according to <https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644985(v=vs.85)>. As far as I can tell, I can't change the signature of my callback function (because it's enforced by <https://docs.rs/winapi/0.3.9/winapi/um/winuser/type.HOOKPROC.html> when calling <https://docs.rs/winapi/0.3.9/winapi/um/winuser/fn.SetWindowsHookExA.html>), and attempting to cast the value of the LPARAM or interpreting LPARAM as a pointer itself both fail.

A gist attempting to reproduce this is at https://gist.github.com/duvallj/29c224ffa208138091f568c00c81e2aa, but I'm not sure if the busyloop there is correct, and I am actually working with https://github.com/duvallj/facestuff-rust.

Any help here is appreciated.

**Comment by duvallj** [comment]
![image](https://user-images.githubusercontent.com/10897431/98007315-3b8e3080-1dc1-11eb-92e3-71fd750137ec.png)
Here is an image of multiple runs of the code; this is why I believe LPARAM may be a pointer value, but attempting to dereference it did not work when I tried.

**Comment by sigod** [comment]
> `let kb_struct_ptr: *const isize = &l_param;`

I think this is a mistake. You're getting the address of `l_param` instead of `l_param` itself.
Try `let kb_struct_ptr: *const isize = l_param as *const isize;`

**Comment by duvallj** [comment]
Ah yup that'd do it, I have no idea why I was trying to do everything in safe Rust there, but using an `unsafe` block for creating the pointer from the val works. Sorry to bother
