### ISSUE TITLE
Helper Implementations for COM Types

### ISSUE THREAD

**Issue by excaliburHisSheath** [retep998/winapi-rs#98]
Winapi-rs has has support for COM types through manually declaring the vtable, but I've noticed that using these types is pretty nasty compared to doing so in C (see [this example](https://github.com/tomaka/cpal/blob/master/src/wasapi/mod.rs#L180)). This could be greatly simplified by adding an impl to the various COM types that wrap up the calls to the vtable functions. I've started implementing this on my fork (see [this commit](https://github.com/excaliburHisSheath/winapi-rs/commit/2d1d204dd011402011fc3ba6a302a1369d9be829)), but I wanted to get some feedback before making a pull request. Is this sort of change in line with the design ethos of winapi-rs? It seems like the idea is to only provide the C bindings to the Windows APIs, so this starts to go beyond that in providing a wrapper around the C bindings to provide a cleaner API. The reason I still think this is a good idea is that it recreates the C++ API that COM is supposed to have, which I would argue still adheres to the design ethos of winapi-rs.

Let me know what you think. If this seems like something worth doing I can make PRs as get things put together.

**Comment by retep998** [comment]
Not worth doing because that's a lot of typing.
What is worth doing is this:
https://github.com/retep998/winapi-rs/commit/c51c581e3e18b1e1179524a5530c9faced41b21f
