### ISSUE TITLE
use winapi::um::memoryapi; | no memoryapi in um   HELP ME!!!

### ISSUE THREAD

**Issue by Yihsiwei** [retep998/winapi-rs#994]
use winapi::um::memoryapi; | no memoryapi in um HELP ME!!!

**Comment by C0D3-M4513R** [comment]
Add the feature "memoryapi". winapi has a lot of features. enable features as needed!

**Comment by Yihsiwei** [comment]
Thank you

**Comment by C0D3-M4513R** [comment]
If that worked, you should close this issue
